export const weapon = {
  StraightSword: [
    {
      id: "Emerald of Genesis",
      kr: "천년의 회류",
      jp: "千古の湖水",
      zh: "千古洑流",
    },
    {
      id: "Blazing Brilliance",
      kr: "솟아오르는 화염",
      jp: "赫く燃ゆる流光",
      zh: "赫奕流明",
    },
    {
      id: "Red Spring",
      kr: "날카로운 봄",
      jp: "春裁ち",
      zh: "裁春",
    },
    {
      id: "Unflickering Valor",
      kr: "흔들리지 않는 용기",
      jp: "エンドレスボヤージュ",
      zh: "不灭航路",
    },
    {
      id: "Bloodpact's Pledge",
      kr: "혈맹의 약속",
      jp: "血の盟約",
      zh: "血誓盟约",
    },
    {
      id: "Somnoire Anchor",
      kr: "마음의 닻",
      jp: "心の錨",
      zh: "心之锚",
    },
    {
      id: "Overture",
      kr: "행진의 서곡",
      jp: "行進オーバーチュア",
      zh: "行进序曲",
    },
    {
      id: "Sword#18",
      kr: "18형 직검·순간의 칼빛",
      jp: "瞬斬刀＃18",
      zh: "瞬斩刀-18型",
    },
    {
      id: "Commando of Conviction",
      kr: "야귀의 신념",
      jp: "決死の一人戦",
      zh: "不归孤军",
    },
    {
      id: "Lunar Cutter",
      kr: "상승의 서녘",
      jp: "倒錯の星",
      zh: "西升",
    },
    {
      id: "Lumingloss",
      kr: "천공의 광경",
      jp: "万象変遷",
      zh: "飞景",
    },
    {
      id: "Endless Collapse",
      kr: "영원의 붕괴",
      jp: "永遠を砕く重力崩壊",
      zh: "永续坍缩",
    },
    {
      id: "Fables of Wisdom",
      kr: "풍류의 우화시",
      jp: "風刺のファブリオー",
      zh: "风流的寓言诗",
    },
  ],
  GreatSword: [
    {
      id: "Lutrous Razor",
      kr: "푸른 물결의 빛",
      jp: "仙境の湖光",
      zh: "浩境粼光",
    },
    {
      id: "Verdant Summit",
      kr: "청룡의 천장",
      jp: "蒼鱗連峰",
      zh: "苍鳞千嶂",
    },
    {
      id: "Ages of Harvest",
      kr: "태평성대",
      jp: "歳華調和",
      zh: "时和岁稔",
    },
    {
      id: "Discord",
      kr: "기묘한 울림",
      jp: "霊感ディスコード",
      zh: "异响空灵",
    },
    {
      id: "Broadblade#41",
      kr: "41형 대검·무거운 책임",
      jp: "重破刃＃41",
      zh: "重破刃-41型",
    },
    {
      id: "Dauntless Evernight",
      kr: "장야의 불빛",
      jp: "長夜の灯火",
      zh: "永夜长明",
    },
    {
      id: "Helios Cleaver",
      kr: "저무는 동녘",
      jp: "逆行の星",
      zh: "东落",
    },
    {
      id: "Autumntrace",
      kr: "가을의 무늬",
      jp: "秋の名残",
      zh: "纹秋",
    },
    {
      id: "Waning Redshift",
      kr: "멸망의 주파수",
      jp: "破滅に迫る赤方偏移",
      zh: "凋亡频移",
    },
    {
      id: "Meditations on Mercy",
      kr: "용서의 명상록",
      jp: "寛恕のタ・エイス・ヘアウトン",
      zh: "容赦的沉思录",
    },
  ],
  Gauntlet: [
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
    {
      id: "",
      kr: "",
      jp: "",
      zh: "",
    },
  ],
  Firearm: [{}],
  Amplifter: [{}],
};

export const weaponStats = {};
