import type { CharacterId } from "./characterStats";

export const WeaponTypes = [
  "sword",
  "broadblade",
  "gauntlet",
  "pistol",
  "rectifier",
] as const;
export type WeaponType = (typeof WeaponTypes)[number];

export const ElementTypes = [
  "aero",
  "glacio",
  "fusion",
  "electro",
  "havoc",
  "spectro",
] as const;
export type ElementType = (typeof ElementTypes)[number];

const AttackTypes = ["basic", "heavy", "skill", "liberation", "heal"] as const;
export type AttackType = (typeof AttackTypes)[number];

export interface Character {
  id: CharacterId;
  en: string;
  kr: string;
  jp: string;
  zh: string;
  hasSkin: boolean;
  weapon: WeaponType;
  element: ElementType;
  type: AttackType;
  version: number;
  isElite: boolean;
  region: //==================================================//
  // | "Scarlet Snow" // = //@ 
  //========================================================//
  | "Spacetrek Collective" // = //@ 스페이스트렉 콜렉티브 (라하이 로이)
  //========================================================//
    | "Spacetrek Collective" // = //@ 스페이스트렉 콜렉티브 (라하이 로이)
    | "Statotchi Academy" // == //@ 스타토치 아카데미 (라하이 로이)
    //========================================================//
    | "Fractsidus" // ========= //@ 잔성회
    | "Seven Hills" // ======== //@ 일곱언덕 (리나시타)
    | "Ragunna" // ============ //@ 라군나 (리나시타)
    //========================================================//  
    | "Black Shores" // ======= //@ 검은해안
    | "Huanglong" // ========== //@ 황룡
    | "Unknown"; // =========== //@ 기타, 알 수 없음
  //==========================================================//
}

export const character: Record<CharacterId, Character> = {
  //$== ver 3.X ===========================//
  //*== ver 3.6 ===========================//
  /* temp: {
    en: "",
    kr: "",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: ,
    element: ,
    type: ,
    version: 3.1,
    isElite: true,
    region: ,
  },*/

  //*== ver 3.5 ===========================//
  /* yangyang_secondary: {
    en: "",
    kr: "",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: ,
    element: ,
    type: ,
    version: 3.1,
    isElite: true,
    region: ,
  },
  suisui: {
    en: "",
    kr: "",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: ,
    element: ,
    type: ,
    version: 3.1,
    isElite: true,
    region: ,
  },*/
  
  //*== ver 3.4 ===========================//
  lucilla: {
    id: "lucilla",
    en: "Lucilla",
    kr: "루실라",
    jp: "ルシラー",
    zh: "洛瑟菈",
    hasSkin: false,
    weapon: "rectifier",
    element: "glacio",
    type: "basic",
    version: 3.4,
    isElite: true,
    region: "Statotchi Academy",
  },
  rebecca: {
    id: "rebecca",
    en: "Rebecca",
    kr: "레베카",
    jp: "レベッカ",
    zh: "丽贝卡",
    hasSkin: false,
    weapon: "pistol",
    element: "electro",
    type: "basic",
    version: 3.4,
    isElite: true,
    region: "Unknown",
  },
  lucy: {
    id: "lucy",
    en: "Lucy",
    kr: "루시",
    jp: "ルーシー",
    zh: "露西",
    hasSkin: false,
    weapon: "pistol",
    element: "spectro",
    type: "heavy",
    version: 3.4,
    isElite: true,
    region: "Unknown",
  },

  //*== ver 3.3 ===========================//
  denia: {
    id: "denia",
    en: "Denia",
    kr: "데니아",
    jp: "stay tune",
    zh: "达妮娅",
    hasSkin: false,
    weapon: "rectifier",
    element: "fusion",
    type: "skill",
    version: 3.3,
    isElite: true,
    region: "Unknown",
  },
  hiyuki: {
    id: "hiyuki",
    en: "Hiyuki",
    kr: "히유키",
    jp: "緋雪",
    zh: "绯雪",
    hasSkin: false,
    weapon: "sword",
    element: "glacio",
    type: "liberation",
    version: 3.3,
    isElite: true,
    region: "Unknown",
  },

  //*== ver 3.2 ===========================//
  sigrika: {
    id: "sigrika",
    en: "Sigrika",
    kr: "시그리카",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "gauntlet",
    element: "aero",
    type: "skill",
    version: 3.2,
    isElite: true,
    region: "Spacetrek Collective",
  },

  //*== ver 3.1 ===========================//
  luuk_herssen: {
    id: "luuk_herssen",
    en: "Luuk Herssen",
    kr: "루크 헤르센",
    jp: "エイメス",
    zh: "爱弥斯",
    hasSkin: false,
    weapon: "gauntlet",
    element: "spectro",
    type: "liberation",
    version: 3.1,
    isElite: true,
    region: "Statotchi Academy",
  },
  aemeath: {
    id: "aemeath",
    en: "Aemeath",
    kr: "에이메스",
    jp: "エイメス",
    zh: "爱弥斯",
    hasSkin: false,
    weapon: "sword",
    element: "fusion",
    type: "liberation",
    version: 3.1,
    isElite: true,
    region: "Statotchi Academy",
  },

  //*== ver 3.0 ===========================//
  mornye: {
    id: "mornye",
    en: "mornye",
    kr: "모니에",
    jp: "モーニエ",
    zh: "莫宁",
    hasSkin: false,
    weapon: "broadblade",
    element: "fusion",
    type: "heal",
    version: 3.0,
    isElite: true,
    region: "Spacetrek Collective",
  },
  lynae: {
    id: "lynae",
    en: "lynae",
    kr: "린네",
    jp: "リンネー",
    zh: "琳奈",
    hasSkin: false,
    weapon: "pistol",
    element: "spectro",
    type: "basic",
    version: 3.0,
    isElite: true,
    region: "Statotchi Academy",
  },

  //$== ver 2.X ===========================//
  //*== ver 2.8 ===========================//
  chisa: {
    id: "chisa",
    en: "chisa",
    kr: "치사",
    jp: "千咲",
    zh: "千咲",
    hasSkin: false,
    weapon: "broadblade",
    element: "havoc",
    type: "liberation",
    version: 2.8,
    isElite: true,
    region: "Statotchi Academy",
  },
  buling: {
    id: "buling",
    en: "buling",
    kr: "복링",
    jp: "卜霊",
    zh: "卜灵",
    hasSkin: false,
    weapon: "rectifier",
    element: "electro",
    type: "heal",
    version: 2.8,
    isElite: false,
    region: "Black Shores",
  },
  
  //*== ver 2.7 ===========================//
  qiuyuan: {
    id: "qiuyuan",
    en: "qiuyuan",
    kr: "구원",
    jp: "仇遠",
    zh: "仇远",
    hasSkin: false,
    weapon: "sword",
    element: "aero",
    type: "heavy",
    version: 2.7,
    isElite: true,
    region: "Huanglong",
  },
  galbrena: {
    id: "galbrena",
    en: "galbrena",
    kr: "갈브레나",
    jp: "ガルブレーナ",
    zh: "嘉贝莉娜",
    hasSkin: false,
    weapon: "pistol",
    element: "fusion",
    type: "heavy",
    version: 2.7,
    isElite: true,
    region: "Black Shores",
  },
  
  //*== ver 2.6 ===========================//
  iuno: {
    id: "iuno",
    en: "iuno",
    kr: "유노",
    jp: "ユーノ",
    zh: "尤诺",
    hasSkin: false,
    weapon: "gauntlet",
    element: "aero",
    type: "liberation",
    version: 2.6,
    isElite: true,
    region: "Seven Hills",
  },
  augusta: {
    id: "augusta",
    en: "augusta",
    kr: "아우구스타",
    jp: "オーガスタ",
    zh: "奥古斯塔",
    hasSkin: false,
    weapon: "broadblade",
    element: "electro",
    type: "heavy",
    version: 2.6,
    isElite: true,
    region: "Seven Hills",
  },
  
  //*== ver 2.5 ===========================//
  phrolova: {
    id: "phrolova",
    en: "phrolova",
    kr: "플로로",
    jp: "フローヴァ",
    zh: "弗洛洛",
    hasSkin: false,
    weapon: "rectifier",
    element: "havoc",
    type: "skill",
    version: 2.5,
    isElite: true,
    region: "Fractsidus",
  },
  
  //*== ver 2.4 ===========================//
  lupa: {
    id: "lupa",
    en: "lupa",
    kr: "루파",
    jp: "ルパ",
    zh: "露帕",
    hasSkin: false,
    weapon: "broadblade",
    element: "fusion",
    type: "liberation",
    version: 2.4,
    isElite: true,
    region: "Ragunna",
  },
  cartethyia: {
    id: "cartethyia",
    en: "cartethyia",
    kr: "카르티시아",
    jp: "カルテジア",
    zh: "卡提希娅",
    hasSkin: false,
    weapon: "sword",
    element: "aero",
    type: "basic",
    version: 2.4,
    isElite: true,
    region: "Ragunna",
  },
  
  //*== ver 2.3 ===========================//
  chiaccona: {
    id: "chiaccona",
    en: "chiaccona",
    kr: "샤콘",
    jp: "シャコンヌ",
    zh: "夏空",
    hasSkin: false,
    weapon: "pistol",
    element: "aero",
    type: "liberation",
    version: 2.3,
    isElite: true,
    region: "Ragunna",
  },
  zani: {
    id: "zani",
    en: "zani",
    kr: "젠니",
    jp: "ザンニー",
    zh: "赞妮",
    hasSkin: false,
    weapon: "gauntlet",
    element: "spectro",
    type: "heavy",
    version: 2.3,
    isElite: true,
    region: "Ragunna",
  },
  
  //*== ver 2.2 ===========================//
  cantarella: {
    id: "cantarella",
    en: "cantarella",
    kr: "칸타렐라",
    jp: "カンタレラ",
    zh: "坎特蕾拉",
    hasSkin: false,
    weapon: "rectifier",
    element: "havoc",
    type: "basic",
    version: 2.2,
    isElite: true,
    region: "Ragunna",
  },
  rover_aero: {
    id: "rover_aero",
    en: "rover : Aero",
    kr: "방랑자 (기류)",
    jp: "漂泊者",
    zh: "漂泊者",
    hasSkin: false,
    weapon: "sword",
    element: "aero",
    type: "heal",
    version: 2.2,
    isElite: true,
    region: "Unknown",
  },

  //*== ver 2.1 ===========================//
  brant: {
    id: "brant",
    en: "brant",
    kr: "브랜트",
    jp: "ブラント",
    zh: "布兰特",
    hasSkin: false,
    weapon: "sword",
    element: "fusion",
    type: "basic",
    version: 2.1,
    isElite: true,
    region: "Ragunna",
  },
  phoebe: {
    id: "phoebe",
    en: "phoebe",
    kr: "페비",
    jp: "フィービー",
    zh: "菲比",
    hasSkin: false,
    weapon: "rectifier",
    element: "spectro",
    type: "heavy",
    version: 2.1,
    isElite: true,
    region: "Ragunna",
  },
  
  //*== ver 2.0 ===========================//
  roccia: {
    id: "roccia",
    en: "roccia",
    kr: "로코코",
    jp: "ロココ",
    zh: "洛可可",
    hasSkin: false,
    weapon: "gauntlet",
    element: "havoc",
    type: "heavy",
    version: 2.0,
    isElite: true,
    region: "Ragunna",
  },
  carlotta: {
    id: "carlotta",
    en: "carlotta",
    kr: "카를로타",
    jp: "カルロッタ",
    zh: "珂莱塔",
    hasSkin: false,
    weapon: "pistol",
    element: "glacio",
    type: "skill",
    version: 2.0,
    isElite: true,
    region: "Ragunna",
  },

  //$== ver 1.X ===========================//
  //*== ver 1.4 ===========================//
  lumi: {
    id: "lumi",
    en: "lumi",
    kr: "루미",
    jp: "灯灯",
    zh: "灯灯",
    hasSkin: false,
    weapon: "broadblade",
    element: "electro",
    type: "skill",
    version: 1.4,
    isElite: false,
    region: "Huanglong",
  },
  camellya: {
    id: "camellya",
    en: "camellya",
    kr: "카멜리아",
    jp: "ツバキ",
    zh: "椿",
    hasSkin: false,
    weapon: "sword",
    element: "havoc",
    type: "basic",
    version: 1.4,
    isElite: true,
    region: "Black Shores",
  },

  //*== ver 1.3 ===========================//
  youhu: {
    id: "youhu",
    en: "youhu",
    kr: "유호",
    jp: "釉瑚",
    zh: "釉瑚",
    hasSkin: false,
    weapon: "gauntlet",
    element: "glacio",
    type: "heal",
    version: 1.3,
    isElite: false,
    region: "Huanglong",
  },
  shorekeeper: {
    id: "shorekeeper",
    en: "shorekeeper",
    kr: "파수인",
    jp: "ショアキーパー",
    zh: "守岸人",
    hasSkin: false,
    weapon: "rectifier",
    element: "spectro",
    type: "heal",
    version: 1.3,
    isElite: true,
    region: "Black Shores",
  },

  //*== ver 1.2 ===========================//
  xiangliyao: {
    id: "xiangliyao",
    en: "xiangliyao",
    kr: "상리요",
    jp: "相里要",
    zh: "相里要",
    hasSkin: false,
    weapon: "gauntlet",
    element: "electro",
    type: "liberation",
    version: 1.2,
    isElite: true,
    region: "Huanglong",
  },
  zhezhi: {
    id: "zhezhi",
    en: "zhezhi",
    kr: "절지",
    jp: "折枝",
    zh: "折枝",
    hasSkin: false,
    weapon: "rectifier",
    element: "glacio",
    type: "skill",
    version: 1.2,
    isElite: true,
    region: "Huanglong",
  },

  //*== ver 1.1 ===========================//
  changli: {
    id: "changli",
    en: "changli",
    kr: "장리",
    jp: "長離",
    zh: "长离",
    hasSkin: false,
    weapon: "sword",
    element: "fusion",
    type: "skill",
    version: 1.1,
    isElite: true,
    region: "Huanglong",
  },
  jinhsi: {
    id: "jinhsi",
    en: "jinhsi",
    kr: "금희",
    jp: "今汐",
    zh: "今汐",
    hasSkin: true,
    weapon: "broadblade",
    element: "spectro",
    type: "skill",
    version: 1.1,
    isElite: true,
    region: "Huanglong",
  },

  //*== ver 1.0 ===========================//
  yinlin: {
    id: "yinlin",
    en: "yinlin",
    kr: "음림",
    jp: "吟霖",
    zh: "吟霖",
    hasSkin: false,
    weapon: "rectifier",
    element: "electro",
    type: "skill",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  jiyan: {
    id: "jiyan",
    en: "jiyan",
    kr: "기염",
    jp: "忌炎",
    zh: "忌炎",
    hasSkin: false,
    weapon: "broadblade",
    element: "aero",
    type: "heavy",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  rover_havoc: {
    id: "rover_havoc",
    en: "rover : Havoc",
    kr: "방랑자 (인멸)",
    jp: "漂泊者",
    zh: "漂泊者",
    hasSkin: false,
    weapon: "sword",
    element: "havoc",
    type: "liberation",
    version: 1.0,
    isElite: true,
    region: "Unknown",
  },

  //$== ver open ===========================//
  //# 5★
  rover_spectro: {
    id: "rover_spectro",
    en: "rover : Spectro",
    kr: "방랑자 (회절)",
    jp: "漂泊者",
    zh: "漂泊者",
    hasSkin: false,
    weapon: "sword",
    element: "spectro",
    type: "liberation",
    version: 1.0,
    isElite: true,
    region: "Unknown",
  },
  verina: {
    id: "verina",
    en: "verina",
    kr: "벨리나",
    jp: "ヴェリーナ",
    zh: "维里奈",
    hasSkin: false,
    weapon: "rectifier",
    element: "spectro",
    type: "heal",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  calcharo: {
    id: "calcharo",
    en: "calcharo",
    kr: "카카루",
    jp: "カカロ",
    zh: "卡卡罗",
    hasSkin: false,
    weapon: "broadblade",
    element: "electro",
    type: "heavy",
    version: 1.0,
    isElite: true,
    region: "Unknown",
  },
  encore: {
    id: "encore",
    en: "encore",
    kr: "앙코",
    jp: "アンコ",
    zh: "安可",
    hasSkin: false,
    weapon: "rectifier",
    element: "fusion",
    type: "basic",
    version: 1.0,
    isElite: true,
    region: "Unknown",
  },
  jianxin: {
    id: "jianxin",
    en: "jianxin",
    kr: "감심",
    jp: "鑑心",
    zh: "鉴心",
    hasSkin: false,
    weapon: "gauntlet",
    element: "aero",
    type: "heavy",
    version: 1.0,
    isElite: true,
    region: "Unknown",
  },
  lingyang: {
    id: "lingyang",
    en: "lingyang",
    kr: "능양",
    jp: "凌陽",
    zh: "凌阳",
    hasSkin: false,
    weapon: "gauntlet",
    element: "glacio",
    type: "basic",
    version: 1.0,
    isElite: true,
    region: "Unknown",
  },
  //# 4★
  sanhua: {
    id: "sanhua",
    en: "sanhua",
    kr: "산화",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "sword",
    element: "glacio",
    type: "skill",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  baizhi: {
    id: "baizhi",
    en: "baizhi",
    kr: "설지",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "rectifier",
    element: "glacio",
    type: "heal",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  chixia: {
    id: "chixia",
    en: "chixia",
    kr: "치샤",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "pistol",
    element: "fusion",
    type: "liberation",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  mortefi: {
    id: "mortefi",
    en: "mortefi",
    kr: "모르테피",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "pistol",
    element: "fusion",
    type: "liberation",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  yuanwu: {
    id: "yuanwu",
    en: "yuanwu",
    kr: "연무",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "gauntlet",
    element: "electro",
    type: "basic",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  yangyang: {
    id: "yangyang",
    en: "yangyang",
    kr: "양양",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "sword",
    element: "aero",
    type: "liberation",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  aalto: {
    id: "aalto",
    en: "aalto",
    kr: "알토",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "pistol",
    element: "aero",
    type: "skill",
    version: 1.0,
    isElite: true,
    region: "Black Shores",
  },
  taoqi: {
    id: "taoqi",
    en: "taoqi",
    kr: "도기",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "broadblade",
    element: "havoc",
    type: "liberation",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
  danjin: {
    id: "danjin",
    en: "danjin",
    kr: "단근",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "sword",
    element: "havoc",
    type: "heavy",
    version: 1.0,
    isElite: true,
    region: "Huanglong",
  },
};

export const characterList = Object.values(character);
export const characterIds = characterList.map((item) => item.id);
