export const character = [
  {
    id: "aalto",
    kr: "알토",
    jp: "アールト",
    zh: "秋水",
    hasSkin: false,
    weapon: "Firearm",
    element: "Aero",
    type: "skill",
  },
  {
    id: "baizhi",
    kr: "설지",
    jp: "白芷(ビャクシ)",
    zh: "白芷",
    hasSkin: false,
    weapon: "Amplifter",
    element: "Glacio",
    type: "heal",
  },
  {
    id: "brant",
    kr: "브랜트",
    jp: "ブラント",
    zh: "布兰特",
    hasSkin: false,
    weapon: "StraightSword",
    element: "Fusion",
    type: "normal",
  },
  {
    id: "calcharo",
    kr: "카카루",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "GreatSword",
    element: "Electro",
    type: "ult",
  },
  {
    id: "camellya",
    kr: "카멜리아",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "StraightSword",
    element: "Havoc",
    type: "normal",
  },
  {
    id: "cantarella",
    kr: "칸타렐라",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Amplifter",
    element: "Havoc",
    type: "heal",
  },
  {
    id: "carlotta",
    kr: "카를로타",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Firearm",
    element: "Glacio",
    type: "skill",
  },
  {
    id: "changli",
    kr: "장리",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "StraightSword",
    element: "Fusion",
    type: "skill",
  },
  {
    id: "chiaccona",
    kr: "샤콘",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Firearm",
    element: "Aero",
    type: "skill",
  },
  {
    id: "chixia",
    kr: "치샤",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Firearm",
    element: "Fusion",
    type: "skill",
  },
  {
    id: "danjin",
    kr: "단근",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "StraightSword",
    element: "Havoc",
    type: "skill",
  },
  {
    id: "encore",
    kr: "앙코",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Amplifter",
    element: "Fusion",
    type: "normal",
  },
  {
    id: "jianxin",
    kr: "감심",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Gauntlet",
    element: "Aero",
    type: "ult",
  },
  {
    id: "jinhsi",
    kr: "금희",
    jp: "",
    zh: "",
    hasSkin: true,
    weapon: "GreatSword",
    element: "Spectro",
    type: "skill",
  },
  {
    id: "jiyan",
    kr: "기염",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "GreatSword",
    element: "Aero",
    type: "heavy",
  },
  {
    id: "lingyang",
    kr: "능양",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Gauntlet",
    element: "Glacio",
    type: "normal",
  },
  {
    id: "lumi",
    kr: "루미",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "GreatSword",
    element: "Aero",
    type: "skill",
  },
  {
    id: "mortefi",
    kr: "모르테피",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Firearm",
    element: "Fusion",
    type: "heavy",
  },
  {
    id: "phoebe",
    kr: "페비",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Amplifter",
    element: "Spectro",
    type: "heavy",
  },
  {
    id: "roccia",
    kr: "로코코",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Gauntlet",
    element: "Havoc",
    type: "heavy",
  },
  {
    id: "rover",
    kr: "공명자",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "StraightSword",
    element: null,
    type: null,
  },
  {
    id: "sanhua",
    kr: "산화",
    jp: "",
    zh: "",
    hasSkin: true,
    weapon: "StraightSword",
    element: "Glacio",
    type: "skill",
  },
  {
    id: "shorekeeper",
    kr: "파수인",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Amplifter",
    element: "Spectro",
    type: "heal",
  },
  {
    id: "taoqi",
    kr: "도기",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "GreatSword",
    element: "Havoc",
    type: "ult",
  },
  {
    id: "verina",
    kr: "벨리나",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Amplifter",
    element: "Spectro",
    type: "heal",
  },
  {
    id: "xiangliyao",
    kr: "상리요",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Gauntlet",
    element: "Electro",
    type: "ult",
  },
  {
    id: "yangyang",
    kr: "양양",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "StraightSword",
    element: "Aero",
    type: "skill",
  },
  {
    id: "yinlin",
    kr: "음림",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Amplifter",
    element: "Electro",
    type: "skill",
  },
  {
    id: "youhu",
    kr: "유호",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Gauntlet",
    element: "Glacio",
    type: "heal",
  },
  {
    id: "yuanwu",
    kr: "연무",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Gauntlet",
    element: "Electro",
    type: "ult",
  },
  {
    id: "zani",
    kr: "젠니",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Gauntlet",
    element: "Spectro",
    type: "heavy",
  },
  {
    id: "zhezhi",
    kr: "절지",
    jp: "",
    zh: "",
    hasSkin: false,
    weapon: "Amplifter",
    element: "Glacio",
    type: "skill",
  },
];
