import type { LangType } from "@/stores/appStore";
import { FixedStats, type StatId } from "./stats";
import { harmony, type HarmonyId } from "./harmonies";
import type { CharacterId } from "./characterStats";
import { character } from "./characters";

export interface EchoRuntime {
  echoId: string;
  harmony: string;
  cost: number;
  mainStat: string;
  subgetStats: () => [string, number][];
  score: number[];
}

export function createEmptyEcho(cost = 1): EchoRuntime {
  return {
    echoId: "default",
    harmony: "default",
    cost: cost,
    mainStat: FixedStats.dummy.id,
    subgetStats: () => [
      ["dummy", -1],
      ["dummy", -1],
      ["dummy", -1],
      ["dummy", -1],
      ["dummy", -1],
    ],
    score: [0.0, 0.0],
  };
}

export interface EchoStat {
  statId: StatId;
  value: number;
}

export interface EchoData {
  id: string;
  en: string;
  kr: string;
  jp: string;
  zh: string;
  type: HarmonyId[];
  getStats: (characterId: CharacterId) => EchoStat[];
}

export type EchoCostKey = "Cost1" | "Cost3" | "Cost4"

export const echoDict: Record<EchoCostKey, Record<string, Omit<EchoData, "id">>> = {
  /*
    asdf: {
      en: "",
      kr: "",
      jp: "",
      zh: "",
      type: [],
      getStats: (_) => [],
    },
  */

  Cost4: {
    X81: {
      en: "Calamity Effigy",
      kr: "하늘의 기관 인형 · 겁살",
      jp: "天傀劫殺",
      zh: "天傀劫煞",
      type: [harmony.Heart.id, harmony.Lamp.id],
      getStats: (_) => [
        { statId: FixedStats.aeroBns.id, value: 20.0 },
      ],
    },
    N91: {
      en: "Thousand-Puppet Pavilion",
      kr: "천괴중루",
      jp: "千傀の重楼",
      zh: "千傀重楼",
      type: [harmony.Song.id],
      getStats: (_) => [
        { statId: FixedStats.havocBns.id, value: 12.0 },
        { statId: FixedStats.heavyBns.id, value: 12.0 },
      ],
    },
    R71: {
      en: "Myriad Snare: Rustfire Chassis",
      kr: "만와뢰 · 잔해",
      jp: "万囮の檻・朽躯",
      zh: "万囮牢·朽躯",
      type: [harmony.Heart.id, harmony.Lamp.id],
      getStats: (_) => [
        { statId: FixedStats.fusionBns.id, value: 12.0 },
        { statId: FixedStats.heavyBns.id, value: 12.0 },
      ],
    },
    X80: {
      en: "Reminiscence - Nightmare: Adam Smasher",
      kr: "공명의 메아리 · 악몽 아담 · 스매셔",
      jp: "響き渡る共鳴・ナイトメア・スマッシャー",
      zh: "共鸣回响·梦魇亚当·重锤",
      type: [harmony.Adam.id],
      getStats: (id) => {
        if (id === character.lucy.id || id === character.rebecca.id)
          return [{ statId: FixedStats.critRate.id, value: 15.0 }];
        return [];
      },
    },
    Z05: {
      en: "Reminiscence: Denia",
      kr: "공명의 메아리 · 데니아",
      jp: "響き渡る共鳴・ダーニャ",
      zh: "共鸣回响·达妮娅",
      type: [harmony.Foam.id],
      getStats: (_) => [],
    },
    Z06: {
      en: "Reminiscence: Threnodian - Voidborne Construct",
      kr: "공명의 메아리 · 명식 · 허무의 신",
      jp: "響き渡る共鳴・鳴式・虚構神機",
      zh: "共鸣回响·鸣式·虚造神型",
      type: [harmony.Snowfall.id],
      getStats: (_) => [
        { statId: FixedStats.glacioBns.id, value: 12.0 },
        { statId: FixedStats.liberationBns.id, value: 12.0 },
      ],
    },
    W89: {
      en: "Nameless Explorer",
      kr: "이름없는 탐색자",
      jp: "名もない探索者",
      zh: "無銘探索者",
      type: [harmony.Sound.id, harmony.Memories.id],
      getStats: (_) => [{ statId: FixedStats.aeroBns.id, value: 12.0 }],
    },
    Z04: {
      en: "Sigillum",
      kr: "시길룸",
      jp: "シギルム",
      zh: "辛吉勒姆",
      type: [harmony.Star.id],
      getStats: (id) => {
        if (id === character.aemeath.id)
          return [{ statId: FixedStats.liberationBns.id, value: 25.0 }];
        return [];
      },
    },
    R65: {
      en: "Hyvatia",
      kr: "하이와티아",
      jp: "ハイヴェイシャ",
      zh: "海維夏",
      type: [harmony.Leap.id, harmony.Revelation.id],
      getStats: (_) => [],
    },
    R66: {
      en: "Reactor Husk",
      kr: "리액터 허스크",
      jp: "ドライブの機骸",
      zh: "爐芯機骸",
      type: [harmony.Halo.id, harmony.Foam.id],
      getStats: (_) => [{ statId: FixedStats.resonanceBns.id, value: 10.0 }],
    },
    //* ==================================================== //
    W75N: {
      en: "Nightmare: Tempest Mephis",
      kr: "악몽 · 천둥의 비늘",
      jp: "ナイトメア・雷刹のウロコ",
      zh: "梦魇·朔雷之鳞",
      type: [harmony.Thunder.id, harmony.Empyrean.id],
      getStats: (_) => [
        { statId: FixedStats.skillBns.id, value: 12.0 },
        { statId: FixedStats.electroBns.id, value: 12.0 },
      ],
    },
    W75: {
      en: "Tempest Mephis",
      kr: "천둥의 비늘",
      jp: "雷刹のウロコ",
      zh: "朔雷之鳞",
      type: [harmony.Thunder.id],
      getStats: (_) => [
        { statId: FixedStats.heavyBns.id, value: 12.0 },
        { statId: FixedStats.electroBns.id, value: 12.0 },
      ],
    },
    H80N: {
      en: "Nightmare: Crownless",
      kr: "악몽 · 크라운리스",
      jp: "ナイトメア・無冠者",
      zh: "梦魇·无冠者",
      type: [harmony.Eclipse.id],
      getStats: (_) => [
        { statId: FixedStats.basicBns.id, value: 12.0 },
        { statId: FixedStats.havocBns.id, value: 12.0 },
      ],
    },
    H80: {
      en: "Crownless",
      kr: "크라운리스",
      jp: "無冠者",
      zh: "无冠者",
      type: [harmony.Eclipse.id],
      getStats: (_) => [
        { statId: FixedStats.skillBns.id, value: 12.0 },
        { statId: FixedStats.havocBns.id, value: 12.0 },
      ],
    },
    H71N: {
      en: "Nightmare: Feilian Beringal",
      kr: "악몽 · 폭주의 고릴라",
      jp: "ナイトメア・飛廉の大猿",
      zh: "梦魇·飞廉之猩",
      type: [harmony.Gale.id],
      getStats: (_) => [
        { statId: FixedStats.heavyBns.id, value: 12.0 },
        { statId: FixedStats.aeroBns.id, value: 12.0 },
      ],
    },
    H71: {
      en: "Feilian Beringal",
      kr: "폭주의 고릴라",
      jp: "飛廉の大猿",
      zh: "飞廉之猩",
      type: [harmony.Gale.id],
      getStats: (_) => [
        { statId: FixedStats.heavyBns.id, value: 12.0 },
        { statId: FixedStats.aeroBns.id, value: 12.0 },
      ],
    },
    N74N: {
      en: "Nightmare: Lampylumen Myriad",
      kr: "악몽 · 반디의 군세",
      jp: "ナイトメア・輝き蛍の軍勢",
      zh: "梦魇·辉萤军势",
      type: [harmony.Frost.id, harmony.Empyrean.id],
      getStats: (_) => [{ statId: FixedStats.glacioBns.id, value: 12.0 }],
    },
    N74: {
      en: "Lampylumen Myriad",
      kr: "반디의 군세",
      jp: "輝き蛍の軍勢",
      zh: "辉萤军势",
      type: [harmony.Frost.id],
      getStats: (_) => [],
    },
    H73N: {
      en: "Nightmare: Mourning Aix",
      kr: "악몽 · 애곡하는 아익스",
      jp: "ナイトメア・哀切の凶鳥",
      zh: "梦魇·哀声鸷",
      type: [harmony.Radiance.id],
      getStats: (_) => [{ statId: FixedStats.spectroBns.id, value: 12.0 }],
    },
    H73: {
      en: "Mourning Aix",
      kr: "애곡하는 아익스",
      jp: "哀切の凶鳥",
      zh: "哀声鸷",
      type: [harmony.Light.id],
      getStats: (_) => [
        { statId: FixedStats.spectroBns.id, value: 12.0 },
        { statId: FixedStats.liberationBns.id, value: 12.0 },
      ],
    },
    R56: {
      en: "Mech Abomination",
      kr: "조립식 로봇",
      jp: "機械アボミネーション",
      zh: "聚械机偶",
      type: [harmony.Tunes.id],
      getStats: (_) => [{ statId: FixedStats.atkPct.id, value: 12.0 }],
    },
    H72N: {
      en: "Nightmare: Impermanence Heron",
      kr: "악몽 · 음험한 백로",
      jp: "ナイトメア・無情のサギ",
      zh: "无常凶鹭",
      type: [harmony.Veil.id],
      getStats: (_) => [
        { statId: FixedStats.heavyBns.id, value: 12.0 },
        { statId: FixedStats.havocBns.id, value: 12.0 },
      ],
    },
    H72: {
      en: "Impermanence Heron",
      kr: "음험한 백로",
      jp: "ナイトメア・無情のサギ",
      zh: "无常凶鹭",
      type: [harmony.Clouds.id],
      getStats: (_) => [],
    },
    H81: {
      en: "Dreamless",
      kr: "무망자",
      jp: "無妄者",
      zh: "无妄者",
      type: [harmony.Eclipse.id],
      getStats: (_) => [],
    },
    Z01: {
      en: "Jué",
      kr: "용의 별자리",
      jp: "角",
      zh: "角",
      type: [harmony.Light.id],
      getStats: (_) => [{ statId: FixedStats.skillBns.id, value: 16.0 }],
    },
    X78: {
      en: "Fallacy of No Return",
      kr: "돌아갈 곳이 없는 오류",
      jp: "フェイタルエラー",
      zh: "无归的谬误",
      type: [harmony.Rejuvent.id],
      getStats: (_) => [
        { statId: FixedStats.atkPct.id, value: 10.0 },
        { statId: FixedStats.resonanceBns.id, value: 10.0 },
      ],
    },
    W83: {
      en: "Lorelei",
      kr: "로렐라이",
      jp: "ローレライ",
      zh: "罗蕾莱",
      type: [harmony.Veil.id],
      getStats: (_) => [
        { statId: FixedStats.havocBns.id, value: 12.0 },
        { statId: FixedStats.basicBns.id, value: 12.0 },
      ],
    },
    W84: {
      en: "Sentry Construct",
      kr: "이성(異性) 무장",
      jp: "ゼノコロッサス",
      zh: "异构武装",
      type: [harmony.Frosty.id],
      getStats: (_) => [
        { statId: FixedStats.skillBns.id, value: 12.0 },
        { statId: FixedStats.glacioBns.id, value: 12.0 },
      ],
    },
    H82: {
      en: "Dragon of Dirge",
      kr: "탄식의 고룡",
      jp: "嘆きのドレイク",
      zh: "叹息古龙",
      type: [harmony.Courage.id],
      getStats: (_) => [
        { statId: FixedStats.fusionBns.id, value: 12.0 },
        { statId: FixedStats.basicBns.id, value: 12.0 },
      ],
    },
    W93: {
      en: "Hecate",
      kr: "헤카테",
      jp: "ヘカテー",
      zh: "赫卡忒",
      type: [harmony.Empyrean.id],
      getStats: (_) => [],
    },
    Z02: {
      en: "Reminiscence: Fleurdelys",
      kr: "공명의 메아리 · 플뢰르 드 리스",
      jp: "響き渡る共鳴・フルールドリス",
      zh: "共鸣回响·芙露德莉斯",
      type: [harmony.Welkin.id, harmony.Pilgrimage.id],
      getStats: (id) => {
        if (id === "cartethyia")
          return [{ statId: FixedStats.aeroBns.id, value: 20.0 }];
        return [{ statId: FixedStats.aeroBns.id, value: 10.0 }];
      },
    },
    W85: {
      en: "Nightmare: Kelpie",
      kr: "악몽 · 켈피",
      jp: "ナイトメア・ケルピー",
      zh: "梦魇·凯尔匹",
      type: [harmony.Welkin.id, harmony.Pilgrimage.id],
      getStats: (_) => [
        { statId: FixedStats.aeroBns.id, value: 12.0 },
        { statId: FixedStats.glacioBns.id, value: 12.0 },
      ],
    },
    W86: {
      en: "Lioness of Glory",
      kr: "영광의 사자",
      jp: "誉れのライオネス",
      zh: "荣耀狮像",
      type: [harmony.Clawprint.id],
      getStats: (_) => [
        { statId: FixedStats.fusionBns.id, value: 12.0 },
        { statId: FixedStats.liberationBns.id, value: 12.0 },
      ],
    },
    W76N: {
      en: "Nightmare: Thundering Mephis",
      kr: "악몽 · 뇌운의 비늘",
      jp: "ナイトメア・雲閃のウロコ",
      zh: "梦魇·云闪之鳞",
      type: [harmony.Thunder.id],
      getStats: (_) => [
        { statId: FixedStats.electroBns.id, value: 12.0 },
        { statId: FixedStats.liberationBns.id, value: 12.0 },
      ],
    },
    H91: {
      en: "Bell-Borne Geochelone",
      kr: "타종 거북이",
      jp: "鳴鐘の亀",
      zh: "鸣钟之龟",
      type: [harmony.Rejuvent.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    W77N: {
      en: "Nightmare: Inferno Rider",
      kr: "악몽 · 지옥불 기사",
      jp: "ナイトメア・燎原の炎騎",
      zh: "梦魇·燎照之骑",
      type: [harmony.Rift.id],
      getStats: (_) => [
        { statId: FixedStats.fusionBns.id, value: 12.0 },
        { statId: FixedStats.skillBns.id, value: 12.0 },
      ],
    },
    W77: {
      en: "Inferno Rider",
      kr: "지옥불 기사",
      jp: "燎原の炎騎",
      zh: "燎照之骑",
      type: [harmony.Rift.id],
      getStats: (_) => [
        { statId: FixedStats.fusionBns.id, value: 12.0 },
        { statId: FixedStats.basicBns.id, value: 12.0 },
      ],
    },
    //$ Update After Phrolobia
    W93N: {
      en: "Nightmare: Hecate",
      kr: "악몽 · 헤카테",
      jp: "ナイトメア・ヘカテー",
      zh: "梦魇·赫卡忒",
      type: [harmony.Dream.id],
      getStats: (_) => [{ statId: FixedStats.havocBns.id, value: 12.0 }],
    },
    X79: {
      en: "Reminiscence: Fenrico",
      kr: "공명의 메아리 · 펜리코",
      jp: "響き渡る共鳴・フェンリコ",
      zh: "共鸣回响·芬莱克",
      type: [harmony.Dream.id, harmony.Law.id],
      getStats: (_) => [
        { statId: FixedStats.aeroBns.id, value: 12.0 },
        { statId: FixedStats.heavyBns.id, value: 12.0 },
      ],
    },
    W87: {
      en: "The False Sovereign",
      kr: "거짓의 신왕",
      jp: "偽りの神王",
      zh: "伪作的神王",
      type: [harmony.Crown.id],
      getStats: (_) => [
        { statId: FixedStats.electroBns.id, value: 12.0 },
        { statId: FixedStats.heavyBns.id, value: 12.0 },
      ],
    },
    W88: {
      en: "Lady of the Sea",
      kr: "바다의 여인",
      jp: "海の娘",
      zh: "海之女",
      type: [harmony.Crown.id],
      getStats: (_) => [
        { statId: FixedStats.aeroBns.id, value: 12.0 },
        { statId: FixedStats.liberationBns.id, value: 12.0 },
      ],
    },
    Z03: {
      en: "Reminiscence: Threnodian - Leviathan",
      kr: "공명의 메아리 · 명식 · 레비아탄",
      jp: "響き渡る共鳴・鳴式・レビヤタン",
      zh: "共鸣回响·鸣式·利维亚坦",
      type: [harmony.Shadow.id, harmony.Fate.id],
      getStats: (_) => [
        { statId: FixedStats.havocBns.id, value: 12.0 },
        { statId: FixedStats.liberationBns.id, value: 12.0 },
      ],
    },
    /*
    "": {
      "en": "Nightmare:",
      "kr": "악몽 · ",
      "jp": "ナイトメア・",
      "zh": "梦魇·",
      "type": [
        harmony..id
      ],
      "stats": [
        {}
      ]
    },
    */
  },
  Cost3: {
    R69: {
      en: "Fog Lionarch",
      kr: "안개 수존",
      jp: "霽息の獣尊",
      zh: "霁息兽尊",
      type: [harmony.Song.id, harmony.Heart.id, harmony.Lamp.id],
      getStats: (_) => [],
    },
    R70: {
      en: "Forbidden Bastion",
      kr: "봉정계유",
      jp: "封庭の械囿",
      zh: "封庭械囿",
      type: [harmony.Song.id, harmony.Heart.id, harmony.Lamp.id],
      getStats: (_) => [{ statId: FixedStats.healBns.id, value: 10.0 }],
    },
    H57: {
      en: "Voidwing Moth",
      kr: "보이드모스",
      jp: "ファントムモス",
      zh: "迷胧幻蛾",
      type: [harmony.Memories.id],
      getStats: (_) => [],
    },
    R67: {
      en: "Kronablight",
      kr: "크로나블라이트",
      jp: "メカファルコン",
      zh: "冠頂械隼",
      type: [harmony.Foam.id, harmony.Star.id],
      getStats: (_) => [],
    },
    X55: {
      en: "Reminiscence: Kronaclaw",
      kr: "공명의 메아리 · 크로나클라우",
      jp: "響き渡る共鳴・クロナファルコン",
      zh: "共鳴迴響·冠頂蒼隼",
      type: [harmony.Foam.id, harmony.Star.id],
      getStats: (_) => [],
    },
    R68: {
      en: "Glommoth",
      kr: "글로모스",
      jp: "グローモス",
      zh: "格洛獁圖",
      type: [harmony.Star.id, harmony.Snowfall.id],
      getStats: (_) => [],
    },
    W74: {
      en: "Windlash Coleoid",
      kr: "바람의 기생갑",
      jp: "風纏いの寄生甲",
      zh: "风鳞蜃甲",
      type: [harmony.Revelation.id, harmony.Snowfall.id],
      getStats: (_) => [],
    },
    W73: {
      en: "Frostbite Coleoid",
      kr: "서리의 기생갑",
      jp: "霜纏いの寄生甲",
      zh: "霜鳞蜃甲",
      type: [harmony.Halo.id, harmony.Snowfall.id],
      getStats: (_) => [],
    },
    R64: {
      en: "Sabercat Prowler",
      kr: "세이버캣 프라울러",
      jp: "プラウラーシェード",
      zh: "隐迹铁影",
      type: [harmony.Leap.id, harmony.Halo.id, harmony.Sound.id],
      getStats: (_) => [],
    },
    R63: {
      en: "Sabercat Reaver",
      kr: "세이버캣 리버",
      jp: "リッパーシェード",
      zh: "锯袭铁影",
      type: [harmony.Leap.id, harmony.Halo.id, harmony.Sound.id],
      getStats: (_) => [],
    },
    R62: {
      en: "Spacetrek Explorer",
      kr: "스페이스 트렉 탐색기",
      jp: "スペーストレック重機",
      zh: "探隧重机",
      type: [harmony.Halo.id, harmony.Foam.id, harmony.Sound.id],
      getStats: (_) => [],
    },
    R61: {
      en: "Ironhoof",
      kr: "아이언후프",
      jp: "アイアン・フーフ",
      zh: "重工铁蹄",
      type: [harmony.Leap.id, harmony.Snowfall.id, harmony.Memories.id],
      getStats: (_) => [],
    },
    R60: {
      en: "Mining Reindeer",
      kr: "마이닝 메카 레인디어",
      jp: "マイニング・メカレインディア",
      zh: "矿岩机麋",
      type: [harmony.Leap.id, harmony.Memories.id],
      getStats: (_) => [],
    },
    R59: {
      en: "Flora Reindeer",
      kr: "플로라 메카 레인디어",
      jp: "フローラ・メカレインディア",
      zh: "莳植机麋",
      type: [harmony.Revelation.id, harmony.Memories.id],
      getStats: (_) => [],
    },
    R58: {
      en: "Twin Nova: Collapsar Blade",
      kr: "트윈 노바 · 콜라사르 블레이드",
      jp: "バイポーラ・アビスフォール",
      zh: "双极·渊陨重锋",
      type: [harmony.Revelation.id, harmony.Star.id, harmony.Sound.id],
      getStats: (_) => [
        { statId: FixedStats.basicBns.id, value: 12.0 },
        { statId: FixedStats.electroBns.id, value: 12.0 },
      ],
    },
    R57: {
      en: "Twin Nova: Nebulous Cannon",
      kr: "트윈 노바 · 네뷸러스 캐논",
      jp: "バイポーラ・ノヴァライザー",
      zh: "双极·星升辉铳",
      type: [harmony.Revelation.id, harmony.Foam.id],
      getStats: (_) => [
        { statId: FixedStats.basicBns.id, value: 12.0 },
        { statId: FixedStats.spectroBns.id, value: 12.0 },
      ],
    },
    S06N: {
      en: "Nightmare: Roseshroom",
      kr: "악몽 · 가시장미버섯",
      jp: "ナイトメア・トゲバラタケ",
      zh: "梦魇·刺玫菇",
      type: [harmony.Fate.id],
      getStats: (_) => [],
    },
    H51: {
      en: "Hoochief",
      kr: "까부는 원숭이",
      jp: "いたずら猿",
      zh: "戏猿",
      type: [harmony.Gale.id, harmony.Rejuvent.id],
      getStats: (_) => [],
    },
    R55: {
      en: "Carapace",
      kr: "트랜스카",
      jp: "恐刃の車",
      zh: "车刃镰",
      type: [harmony.Gale.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    X53: {
      en: "Autopuppet Scout",
      kr: "경전차 로봇",
      jp: "巡回のカラクリ",
      zh: "巡哨机傀",
      type: [harmony.Frost.id, harmony.Light.id],
      getStats: (_) => [],
    },
    H53: {
      en: "Glacio Dreadmane",
      kr: "갈기늑대 · 눈꽃",
      jp: "雪鬣狼",
      zh: "雪鬃狼",
      type: [harmony.Frost.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    Z11: {
      en: "Lumiscale Construct",
      kr: "용비늘의 기축",
      jp: "浮遊鱗機（ふゆうりんき）",
      zh: "游鳞机枢",
      type: [harmony.Frost.id, harmony.Thunder.id],
      getStats: (_) => [],
    },
    H54: {
      en: "Lightcrusher",
      kr: "흑월의 야수",
      jp: "光踏獣（こうとうじゅう）",
      zh: "踏光兽",
      type: [harmony.Light.id],
      getStats: (_) => [],
    },
    W64: {
      en: "Questless Knight",
      kr: "방랑 기사",
      jp: "回歴の騎士",
      zh: "巡游骑士",
      type: [harmony.Frosty.id, harmony.Veil.id],
      getStats: (_) => [],
    },
    W65: {
      en: "Diurnus Knight",
      kr: "백야 기사",
      jp: "炎昼の騎士",
      zh: "幻昼骑士",
      type: [harmony.Radiance.id],
      getStats: (_) => [],
    },
    W66: {
      en: "Nocturnus Knight",
      kr: "흑야 기사",
      jp: "闇夜の騎士",
      zh: "暗夜骑士",
      type: [harmony.Veil.id, harmony.Empyrean.id],
      getStats: (_) => [],
    },
    W67: {
      en: "Abyssal Patricius",
      kr: "파트리시우스 귀족",
      jp: "アビサル・パトリシウス",
      zh: "毒冠贵族",
      type: [harmony.Frosty.id, harmony.Empyrean.id],
      getStats: (_) => [],
    },
    W68: {
      en: "Abyssal Gladius",
      kr: "글라디우스 귀족",
      jp: "アビサル・グラディウス",
      zh: "持刃贵族",
      type: [harmony.Veil.id, harmony.Courage.id],
      getStats: (_) => [],
    },
    W69: {
      en: "Abyssal Mercator",
      kr: "메르카토르 귀족",
      jp: "アビサル・メルカトル",
      zh: "凝水贵族",
      type: [harmony.Frosty.id, harmony.Radiance.id],
      getStats: (_) => [],
    },
    R41: {
      en: "Chop Chop",
      kr: "유령 인형",
      jp: "フロートアルマ",
      zh: "浮灵偶",
      type: [harmony.Empyrean.id, harmony.Courage.id, harmony.Dream.id],
      getStats: (_) => [],
    },
    W70: {
      en: "Vitreum Dancer",
      kr: "블레이드 댄서",
      jp: "ヴィトルムダンサー",
      zh: "琉璃刀伶",
      type: [harmony.Radiance.id, harmony.Empyrean.id],
      getStats: (_) => [],
    },
    R42: {
      en: "Cuddle Wuddle",
      kr: "거대 인형",
      jp: "ビッグベア",
      zh: "巨布偶",
      type: [harmony.Frosty.id, harmony.Veil.id],
      getStats: (_) => [],
    },
    S56: {
      en: "Rage Against the Statue",
      kr: "조각상을 재구성하는 돌멩이",
      jp: "彫像を再構築する岩拳",
      zh: "重塑雕像的拳砾",
      type: [harmony.Radiance.id, harmony.Welkin.id, harmony.Empyrean.id],
      getStats: (_) => [],
    },
    H47: {
      en: "Hurriclaw",
      kr: "소용돌이 곰",
      jp: "ハリケーン熊",
      zh: "飓力熊",
      type: [harmony.Courage.id, harmony.Welkin.id, harmony.Crown.id],
      getStats: (_) => [],
    },
    W71: {
      en: "Capitaneus",
      kr: "카피타네우스",
      jp: "カピタネウス",
      zh: "荣光节使",
      type: [harmony.Radiance.id, harmony.Welkin.id, harmony.Pilgrimage.id],
      getStats: (_) => [
        { statId: FixedStats.spectroBns.id, value: 12.0 },
        { statId: FixedStats.heavyBns.id, value: 12.0 },
      ],
    },
    W72: {
      en: "Pilgrim's Shell",
      kr: "전도사의 경지",
      jp: "伝道師の空殻",
      zh: "传道者的遗形",
      type: [harmony.Pilgrimage.id, harmony.Clawprint.id],
      getStats: (_) => [],
    },
    H55: {
      en: "Kerasaur",
      kr: "케라사우르스",
      jp: "クラトスクス",
      zh: "角鳄",
      type: [harmony.Pilgrimage.id, harmony.Clawprint.id, harmony.Shadow.id],
      getStats: (_) => [
        { statId: FixedStats.aeroBns.id, value: 12.0 },
        { statId: FixedStats.liberationBns.id, value: 12.0 },
      ],
    },
    H56: {
      en: "Corrosaurus",
      kr: "코로사우루스",
      jp: "コロサウルス",
      zh: "蝕脊龍",
      type: [harmony.Clawprint.id, harmony.Shadow.id],
      getStats: (_) => [{ statId: FixedStats.fusionBns.id, value: 12.0 }],
    },
    H42N: {
      en: "Nightmare: Violet-Feathered Heron",
      kr: "악몽 · 보라색 왜가리",
      jp: "ナイトメア・紫羽サギ",
      zh: "梦魇·紫羽鹭",
      type: [harmony.Crown.id],
      getStats: (_) => [],
    },
    H42: {
      en: "Violet-Feathered Heron",
      kr: "보라색 왜가리",
      jp: "紫羽サギ",
      zh: "紫羽鹭",
      type: [harmony.Rift.id, harmony.Thunder.id],
      getStats: (_) => [],
    },
    H41N: {
      en: "Nightmare: Cyan-Feathered Heron",
      kr: "악몽 · 초록색 왜가리",
      jp: "ナイトメア・青羽サギ",
      zh: "梦魇·青羽鹭",
      type: [harmony.Law.id],
      getStats: (_) => [],
    },
    H41: {
      en: "Cyan-Feathered Heron",
      kr: "초록색 왜가리",
      jp: "青羽サギ",
      zh: "青羽鹭",
      type: [harmony.Gale.id, harmony.Light.id],
      getStats: (_) => [],
    },
    S55: {
      en: "Stonewall Bracer",
      kr: "거암 투사",
      jp: "巨岩の闘士",
      zh: "坚岩斗士",
      type: [harmony.Rejuvent.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    W61: {
      en: "Flautist",
      kr: "마접의 악사",
      jp: "宣諭の楽手",
      zh: "奏谕乐师",
      type: [harmony.Thunder.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    W60: {
      en: "Tambourinist",
      kr: "초혼의 악사",
      jp: "金鈴の楽手",
      zh: "振铎乐师",
      type: [harmony.Frost.id, harmony.Eclipse.id],
      getStats: (_) => [],
    },
    W63: {
      en: "Rocksteady Guardian",
      kr: "불굴의 호위",
      jp: "磐石の守り手",
      zh: "磐石守卫",
      type: [harmony.Light.id, harmony.Rejuvent.id],
      getStats: (_) => [],
    },
    W62: {
      en: "Chasm Guardian",
      kr: "심연의 위병",
      jp: "冥淵の守り手",
      zh: "冥渊守卫",
      type: [harmony.Rejuvent.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    H46N: {
      en: "Nightmare: Viridblaze Saurian",
      kr: "악몽 · 그린멜팅카멜레온",
      jp: "ナイトメア・熔解トカゲ",
      zh: "梦魇·绿熔蜥",
      type: [harmony.Shadow.id],
      getStats: (_) => [],
    },
    H46: {
      en: "Viridblaze Saurian",
      kr: "그린멜팅카멜레온",
      jp: "熔解トカゲ",
      zh: "绿熔蜥",
      type: [harmony.Rift.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    S06: {
      en: "Roseshroom",
      kr: "가시장미버섯",
      jp: "トゲバラタケ",
      zh: "刺玫菇",
      type: [harmony.Frost.id, harmony.Eclipse.id],
      getStats: (_) => [],
    },
    H49: {
      en: "Havoc Dreadmane",
      kr: "갈기늑대 · 암흑",
      jp: "闇鬣狼",
      zh: "暗鬃狼",
      type: [harmony.Rift.id, harmony.Eclipse.id],
      getStats: (_) => [],
    },
    H48: {
      en: "Spearback",
      kr: "화살곰",
      jp: "黒棘熊",
      zh: "箭簇熊",
      type: [harmony.Clouds.id, harmony.Eclipse.id],
      getStats: (_) => [],
    },
    W60N: {
      en: "Nightmare: Tambourinist",
      kr: "악몽 · 초혼의 악사",
      jp: "ナイトメア・金鈴の楽手",
      zh: "梦魇·振鐸樂師",
      type: [harmony.Dream.id],
      getStats: (_) => [],
    },
  },
  Cost1: {
    R13: {
      en: "Porcelain Picket",
      kr: "자정후",
      jp: "磁器の庭候",
      zh: "瓷庭候",
      type: [harmony.Lamp.id],
      getStats: (_) => [],
    },
    R14: {
      en: "Stone Picket",
      kr: "석정후",
      jp: "石の庭候",
      zh: "石庭候",
      type: [harmony.Lamp.id],
      getStats: (_) => [],
    },
    R15: {
      en: "Aureate Picket",
      kr: "금정후",
      jp: "金鉄の庭候",
      zh: "金庭候",
      type: [harmony.Heart.id],
      getStats: (_) => [],
    },
    R16: {
      en: "Kernel Puppet: Joy",
      kr: "심월 인형 · 희(喜)",
      jp: "心傀・喜",
      zh: "心傀·喜",
      type: [harmony.Song.id],
      getStats: (_) => [],
    },
    R17: {
      en: "Kernel Puppet: Anger",
      kr: "심월 인형 · 노(怒)",
      jp: "心傀・怒",
      zh: "心傀·怒",
      type: [harmony.Heart.id],
      getStats: (_) => [],
    },
    R18: {
      en: "Kernel Puppet: Worry",
      kr: "심월 인형 · 우(憂)",
      jp: "心傀・憂",
      zh: "心傀·忧",
      type: [harmony.Heart.id],
      getStats: (_) => [],
    },
    R19: {
      en: "Kernel Puppet: Reflection",
      kr: "심월 인형 · 사(思)",
      jp: "心傀・思",
      zh: "心傀·思",
      type: [harmony.Heart.id],
      getStats: (_) => [],
    },
    R20: {
      en: "Kernel Puppet: Grief",
      kr: "심월 인형 · 비(悲)",
      jp: "心傀・悲",
      zh: "心傀·悲",
      type: [harmony.Lamp.id],
      getStats: (_) => [],
    },
    R21: {
      en: "Kernel Puppet: Fright",
      kr: "심월 인형 · 공(恐)",
      jp: "心傀・恐",
      zh: "心傀·恐",
      type: [harmony.Lamp.id],
      getStats: (_) => [],
    },
    R22: {
      en: "Fog Lionarch: Body",
      kr: "안개 수존 · 몸",
      jp: "霽息の獣尊・胴",
      zh: "霁息兽尊·身",
      type: [harmony.Song.id],
      getStats: (_) => [],
    },
    R23: {
      en: "Fog Lionarch: Head",
      kr: "안개 수존 · 머리",
      jp: "霽息の獣尊・首",
      zh: "霁息兽尊·首",
      type: [harmony.Song.id],
      getStats: (_) => [],
    },
    W40: {
      en: "Smiter",
      kr: "분해된 전사",
      jp: "融躯の戦士",
      zh: "融躯战士",
      type: [harmony.Song.id],
      getStats: (_) => [],
    },
    W41: {
      en: "Smolder",
      kr: "불씨의 사냥꾼",
      jp: "熄えぬ狩人",
      zh: "不熄猎手",
      type: [harmony.Song.id],
      getStats: (_) => [],
    },
    W38: {
      en: "Iceglint Dancer",
      kr: "아이스글린트 댄서",
      jp: "アイスグリントダンサー",
      zh: "冰盈舞者",
      type: [harmony.Star.id, harmony.Snowfall.id, harmony.Memories.id],
      getStats: (_) => [],
    },
    W39: {
      en: "Shadow Stepper",
      kr: "쉐도우 스태퍼",
      jp: "シャドウステッパー",
      zh: "影爍者",
      type: [harmony.Star.id, harmony.Foam.id, harmony.Snowfall.id],
      getStats: (_) => [],
    },
    W37: {
      en: "Zip Zap",
      kr: "삐리릭",
      jp: "ビリリ",
      zh: "噼啪啪",
      type: [
        harmony.Leap.id,
        harmony.Revelation.id,
        harmony.Foam.id,
        harmony.Sound.id,
      ],
      getStats: (_) => [],
    },
    R12: {
      en: "Geospider S4",
      kr: "바위거미 S4형",
      jp: "イワグモS4型",
      zh: "岩蛛S4型",
      type: [harmony.Leap.id, harmony.Halo.id, harmony.Star.id],
      getStats: (_) => [],
    },
    R11: {
      en: "Mining Drone",
      kr: "바위 호박벌",
      jp: "サイクツクマバチ",
      zh: "矿岩熊蜂",
      type: [
        harmony.Halo.id,
        harmony.Revelation.id,
        harmony.Sound.id,
        harmony.Memories.id,
      ],
      getStats: (_) => [],
    },
    R10: {
      en: "Flora Drone",
      kr: "파종 호박벌",
      jp: "カフンクマバチ",
      zh: "莳植熊蜂",
      type: [
        harmony.Leap.id,
        harmony.Revelation.id,
        harmony.Sound.id,
        harmony.Memories.id,
      ],
      getStats: (_) => [],
    },
    W36: {
      en: "Tremor Warrior",
      kr: "전율하는 전사",
      jp: "戦慄の戦士",
      zh: "颤栗战士",
      type: [harmony.Halo.id, harmony.Foam.id, harmony.Snowfall.id],
      getStats: (_) => [],
    },
    H22N: {
      en: "Nightmare: Dwarf Cassowary",
      kr: "악몽 · 피그미타조",
      jp: "ナイトメア・地駝鳥",
      zh: "梦魇·侏侏鸵",
      type: [harmony.Fate.id],
      getStats: (_) => [],
    },
    G04N: {
      en: "Nightmare: Tick Tack",
      kr: "악몽 · 우글글",
      jp: "ナイトメア・ウカカ",
      zh: "梦魇·呜咔咔",
      type: [harmony.Fate.id],
      getStats: (_) => [],
    },
    H19: {
      en: "Hooscamp",
      kr: "어린 원숭이",
      jp: "猿の幼体",
      zh: "幼猿",
      type: [harmony.Gale.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    H11: {
      en: "Diamondclaw",
      kr: "결정화 전갈",
      jp: "結晶化サソリ",
      zh: "晶螯蝎",
      type: [harmony.Clouds.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    H02: {
      en: "Chirpuff",
      kr: "쮸쮸복어",
      jp: "ジュルッポ",
      zh: "啾啾河豚",
      type: [harmony.Gale.id, harmony.Eclipse.id],
      getStats: (_) => [],
    },
    X54: {
      en: "Traffic Illuminator",
      kr: "신호등 로봇",
      jp: "信号機モドキ",
      zh: "通行灯偶",
      type: [harmony.Rift.id, harmony.Thunder.id, harmony.Gale.id],
      getStats: (_) => [],
    },
    G05: {
      en: "Clang Bang",
      kr: "딩동동",
      jp: "チリン",
      zh: "叮咚咚",
      type: [harmony.Frost.id, harmony.Light.id],
      getStats: (_) => [],
    },
    H21: {
      en: "Lava Larva",
      kr: "용암 벌레",
      jp: "溶岩虫",
      zh: "融火虫",
      type: [harmony.Rift.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    H22: {
      en: "Dwarf Cassowary",
      kr: "피그미타조",
      jp: "地駝鳥",
      zh: "侏侏鸵",
      type: [harmony.Gale.id, harmony.Rejuvent.id],
      getStats: (_) => [],
    },
    H23: {
      en: "Galescourge Stalker",
      kr: "갈기늑대 · 바람",
      jp: "風鬣狼",
      zh: "风鬃狼",
      type: [harmony.Frosty.id, harmony.Empyrean.id],
      getStats: (_) => [],
    },
    H24: {
      en: "Voltscourge Stalker",
      kr: "갈기늑대 · 천둥",
      jp: "雷鬣狼",
      zh: "雷鬃狼",
      type: [harmony.Veil.id, harmony.Empyrean.id],
      getStats: (_) => [],
    },
    H25: {
      en: "Frostscourge Stalker",
      kr: "갈기늑대 · 서리",
      jp: "霜鬣狼",
      zh: "霜鬃狼",
      type: [harmony.Radiance.id, harmony.Veil.id],
      getStats: (_) => [],
    },
    R01: {
      en: "Chop Chop: Headless",
      kr: "유령 인형 · 헤드",
      jp: "フロートアルマ・ヘッド",
      zh: "浮灵偶·海德",
      type: [harmony.Radiance.id, harmony.Courage.id],
      getStats: (_) => [],
    },
    R02: {
      en: "Chop Chop: Leftless",
      kr: "유령 인형 · 레프",
      jp: "フロートアルマ・レフト",
      zh: "浮灵偶·蕾弗",
      type: [harmony.Frosty.id, harmony.Courage.id],
      getStats: (_) => [],
    },
    R03: {
      en: "Chop Chop: Rightless",
      kr: "유령 인형 · 라잇",
      jp: "フロートアルマ・ライト",
      zh: "浮灵偶·莱特",
      type: [harmony.Frosty.id, harmony.Courage.id],
      getStats: (_) => [],
    },
    R04: {
      en: "Fae Ignis",
      kr: "페이 이그니스",
      jp: "フェイイグニス",
      zh: "幽翎火",
      type: [harmony.Radiance.id, harmony.Veil.id, harmony.Dream.id],
      getStats: (_) => [],
    },
    R05: {
      en: "Nimbus Wraith",
      kr: "구름 바다 요정",
      jp: "雲の妖精",
      zh: "云海妖精",
      type: [harmony.Veil.id, harmony.Empyrean.id, harmony.Shadow.id],
      getStats: (_) => [],
    },
    R06: {
      en: "Hocus Pocus",
      kr: "미스터 매직",
      jp: "ミスター・マギア",
      zh: "魔术先生",
      type: [harmony.Frosty.id, harmony.Empyrean.id],
      getStats: (_) => [],
    },
    R07: {
      en: "Lottie Lost",
      kr: "쓸쓸한 아가씨",
      jp: "ミス・ロンリー",
      zh: "寂寞小姐",
      type: [harmony.Frosty.id, harmony.Courage.id],
      getStats: (_) => [],
    },
    R08: {
      en: "Diggy Duggy",
      kr: "근무 인형",
      jp: "サクサクベア",
      zh: "工头布偶",
      type: [harmony.Radiance.id, harmony.Courage.id],
      getStats: (_) => [],
    },
    R09: {
      en: "Chest Mimic",
      kr: "미믹",
      jp: "秘蔵ミミック",
      zh: "欺诈奇藏",
      type: [harmony.Frosty.id, harmony.Veil.id, harmony.Empyrean.id],
      getStats: (_) => [],
    },
    S10: {
      en: "Golden Junrock",
      kr: "금석 암괴",
      jp: "愚者のゴールドの岩塊",
      zh: "愚金幼岩",
      type: [harmony.Frosty.id, harmony.Radiance.id, harmony.Law.id],
      getStats: (_) => [],
    },
    S11: {
      en: "Calcified Junrock",
      kr: "유약 암괴",
      jp: "ミカーレの岩塊",
      zh: "釉变幼岩",
      type: [harmony.Empyrean.id, harmony.Courage.id, harmony.Crown.id],
      getStats: (_) => [],
    },
    N15: {
      en: "Aero Prism",
      kr: "기류 프리즘",
      jp: "気動のプリズム",
      zh: "气动棱镜",
      type: [harmony.Radiance.id, harmony.Courage.id],
      getStats: (_) => [],
    },
    W32: {
      en: "La Guardia",
      kr: "라 과디어",
      jp: "ガルディア",
      zh: "卫冕节使",
      type: [harmony.Veil.id, harmony.Welkin.id, harmony.Clawprint.id],
      getStats: (_) => [],
    },
    W33: {
      en: "Sagittario",
      kr: "사지타리오",
      jp: "サジタリオ",
      zh: "赦罪节使",
      type: [harmony.Radiance.id, harmony.Welkin.id, harmony.Clawprint.id],
      getStats: (_) => [],
    },
    W34: {
      en: "Sacerdos",
      kr: "사체르도스",
      jp: "サケルドス",
      zh: "慈悲节使",
      type: [harmony.Welkin.id, harmony.Pilgrimage.id],
      getStats: (_) => [],
    },
    H26: {
      en: "Aero Drake",
      kr: "드레이크 · 기류",
      jp: "ドレイクの幼体・気動",
      zh: "小翼龙·气动",
      type: [harmony.Courage.id, harmony.Welkin.id, harmony.Clawprint.id],
      getStats: (_) => [],
    },
    H27: {
      en: "Electro Drake",
      kr: "드레이크 · 전도",
      jp: "ドレイクの幼体・電導",
      zh: "小翼龙·导电",
      type: [harmony.Veil.id, harmony.Welkin.id, harmony.Clawprint.id],
      getStats: (_) => [],
    },
    H28: {
      en: "Glacio Drake",
      kr: "드레이크 · 응결",
      jp: "ドレイクの幼体・凝縮",
      zh: "小翼龙·冷凝",
      type: [harmony.Welkin.id, harmony.Pilgrimage.id],
      getStats: (_) => [],
    },
    H29: {
      en: "Fusion Drake",
      kr: "드레이크 · 용융",
      jp: "ドレイクの幼体・焦熱",
      zh: "小翼龙·热熔",
      type: [harmony.Pilgrimage.id, harmony.Clawprint.id],
      getStats: (_) => [],
    },
    H30: {
      en: "Spectro Drake",
      kr: "드레이크 · 회절",
      jp: "ドレイクの幼体・回折",
      zh: "小翼龙·衍射",
      type: [harmony.Pilgrimage.id, harmony.Clawprint.id],
      getStats: (_) => [],
    },
    H31: {
      en: "Havoc Drake",
      kr: "드레이크 · 인멸",
      jp: "ドレイクの幼体・消滅",
      zh: "小翼龙·湮灭",
      type: [harmony.Pilgrimage.id, harmony.Clawprint.id],
      getStats: (_) => [],
    },
    W35: {
      en: "Devotee's Flesh",
      kr: "고행자의 인형",
      jp: "狂信者の血肉",
      zh: "苦信者的作俑",
      type: [harmony.Welkin.id, harmony.Pilgrimage.id, harmony.Clawprint.id],
      getStats: (_) => [],
    },
    S08: {
      en: "Vanguard Junrock",
      kr: "선봉 암괴",
      jp: "先兵岩塊",
      zh: "先锋幼岩",
      type: [harmony.Thunder.id, harmony.Rejuvent.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    S09: {
      en: "Fission Junrock",
      kr: "분열 암괴",
      jp: "壊れかけ岩塊",
      zh: "裂变幼岩",
      type: [harmony.Thunder.id, harmony.Rejuvent.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    W25: {
      en: "Electro Predator",
      kr: "경칩의 사냥꾼",
      jp: "春雷の狩人",
      zh: "惊蛰猎手",
      type: [harmony.Rift.id, harmony.Thunder.id],
      getStats: (_) => [],
    },
    W30: {
      en: "Fusion Warrior",
      kr: "오열하는 전사",
      jp: "慟哭の戦士",
      zh: "鸣泣战士",
      type: [harmony.Rift.id, harmony.Thunder.id, harmony.Gale.id],
      getStats: (_) => [],
    },
    W31: {
      en: "Havoc Warrior",
      kr: "심판하는 전사",
      jp: "審判の戦士",
      zh: "审判战士",
      type: [harmony.Light.id, harmony.Eclipse.id],
      getStats: (_) => [],
    },
    G02: {
      en: "Snip Snap",
      kr: "칵찰찰",
      jp: "カチャチャ",
      zh: "咔嚓嚓",
      type: [harmony.Rift.id, harmony.Rejuvent.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    G03: {
      en: "Zig Zag",
      kr: "아즈즈",
      jp: "アツツ",
      zh: "阿嗞嗞",
      type: [harmony.Light.id, harmony.Clouds.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    G01: {
      en: "Whiff Whaff",
      kr: "후슈슈",
      jp: "フシュシュ",
      zh: "呼咻咻",
      type: [harmony.Gale.id, harmony.Rejuvent.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    G04: {
      en: "Tick Tack",
      kr: "우글글",
      jp: "ウカカ",
      zh: "呜咔咔",
      type: [harmony.Eclipse.id, harmony.Rejuvent.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    W26: {
      en: "Glacio Predator",
      kr: "상강의 사냥꾼",
      jp: "破霜の狩人",
      zh: "破霜猎手",
      type: [harmony.Frost.id, harmony.Light.id],
      getStats: (_) => [],
    },
    W27: {
      en: "Aero Predator",
      kr: "부메랑 사냥꾼",
      jp: "徘徊の狩人",
      zh: "巡徊猎手",
      type: [harmony.Thunder.id, harmony.Gale.id],
      getStats: (_) => [],
    },
    H12: {
      en: "Cruisewing",
      kr: "순회나비",
      jp: "遊弋蝶",
      zh: "游弋蝶",
      type: [harmony.Light.id, harmony.Rejuvent.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    H08: {
      en: "Sabyr Boar",
      kr: "쇄아멧돼지",
      jp: "砕牙イノシシ",
      zh: "碎獠猪",
      type: [harmony.Frost.id, harmony.Gale.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    H01: {
      en: "Gulpuff",
      kr: "꾹꾹복어",
      jp: "グルッポ",
      zh: "咕咕河豚",
      type: [harmony.Frost.id, harmony.Light.id],
      getStats: (_) => [],
    },
    H05: {
      en: "Excarat",
      kr: "두더지",
      jp: "モグロン",
      zh: "遁地鼠",
      type: [harmony.Frost.id, harmony.Eclipse.id],
      getStats: (_) => [],
    },
    H06: {
      en: "Baby Viridblaze Saurian",
      kr: "그린멜팅카멜레온(유체)",
      jp: "熔解トカゲ（幼体）",
      zh: "绿熔蜥（稚形）",
      type: [harmony.Rift.id, harmony.Thunder.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    S05: {
      en: "Young Roseshroom",
      kr: "가시장미버섯(유체)",
      jp: "トゲバラタケ（幼体）",
      zh: "刺玫菇（稚形）",
      type: [harmony.Gale.id, harmony.Eclipse.id],
      getStats: (_) => [],
    },
    H09: {
      en: "Fusion Dreadmane",
      kr: "갈기늑대 · 불꽃",
      jp: "火鬣狼",
      zh: "火鬃狼",
      type: [harmony.Rift.id, harmony.Rejuvent.id],
      getStats: (_) => [],
    },
    H15: {
      en: "Hoartoise",
      kr: "서릿땅거북",
      jp: "寒霜亀",
      zh: "寒霜陆龟",
      type: [harmony.Frost.id, harmony.Light.id],
      getStats: (_) => [],
    },
    N12: {
      en: "Fusion Prism",
      kr: "용융 프리즘",
      jp: "焦熱のプリズム",
      zh: "热熔棱镜",
      type: [harmony.Frost.id, harmony.Rift.id, harmony.Tunes.id],
      getStats: (_) => [],
    },
    N11: {
      en: "Glacio Prism",
      kr: "응결 프리즘",
      jp: "凝縮のプリズム",
      zh: "冷凝棱镜",
      type: [harmony.Frost.id, harmony.Eclipse.id, harmony.Clouds.id],
      getStats: (_) => [],
    },
    N14: {
      en: "Spectro Prism",
      kr: "회절 프리즘",
      jp: "回折のプリズム",
      zh: "衍射棱镜",
      type: [harmony.Rift.id, harmony.Thunder.id, harmony.Light.id],
      getStats: (_) => [],
    },
    N13: {
      en: "Havoc Prism",
      kr: "인멸 프리즘",
      jp: "消滅のプリズム",
      zh: "湮灭棱镜",
      type: [harmony.Thunder.id, harmony.Light.id, harmony.Eclipse.id],
      getStats: (_) => [],
    },
    W31N: {
      en: "Nightmare: Havoc Warrior",
      kr: "악몽 · 심판하는 전사",
      jp: "ナイトメア・審判の戦士",
      zh: "梦魇·审判战士",
      type: [harmony.Dream.id],
      getStats: (_) => [],
    },
    W26N: {
      en: "Nightmare: Glacio Predator",
      kr: "악몽 · 상강의 사냥꾼",
      jp: "ナイトメア・破霜の狩人",
      zh: "梦魇·破霜猎手",
      type: [harmony.Dream.id],
      getStats: (_) => [],
    },
    W25N: {
      en: "Nightmare: Electro Predator",
      kr: "악몽 · 경칩의 사냥꾼",
      jp: "梦魇·惊蛰猎手",
      zh: "梦魇·赫卡忒",
      type: [harmony.Crown.id],
      getStats: (_) => [],
    },
    W27N: {
      en: "Nightmare: Aero Predator",
      kr: "악몽 · 부메랑 사냥꾼",
      jp: "ナイトメア・徘徊の狩人",
      zh: "梦魇·巡徊猎手",
      type: [harmony.Crown.id],
      getStats: (_) => [],
    },
    H01N: {
      en: "Nightmare: Gulpuff",
      kr: "악몽 · 꾹꾹 복어",
      jp: "ナイトメア・グルッポ",
      zh: "梦魇·咕咕河豚",
      type: [harmony.Law.id],
      getStats: (_) => [],
    },
    H02N: {
      en: "Nightmare: Chirpuff",
      kr: "악몽 · 쮸쮸 복어",
      jp: "ナイトメア・ジュルッポ",
      zh: "梦魇·啾啾河豚",
      type: [harmony.Law.id],
      getStats: (_) => [],
    },
    H06N: {
      en: "Nightmare: Baby Viridblaze Saurian",
      kr: "악몽 · 그린멜팅카멜레온(유체)",
      jp: "ナイトメア・熔解トカゲ（幼体）",
      zh: "梦魇·绿熔蜥（稚形）",
      type: [harmony.Shadow.id],
      getStats: (_) => [],
    },
    S05N: {
      en: "Nightmare: Baby Roseshroom",
      kr: "악몽 · 가시장미버섯(유체)",
      jp: "ナイトメア・トゲバラタケ（幼体）",
      zh: "梦魇·刺玫菇（稚形）",
      type: [harmony.Shadow.id],
      getStats: (_) => [],
    },
  },
};

export type EchoId = keyof (typeof echoDict)[keyof typeof echoDict];

export const ECHO_CANDIDATES: Record<LangType, { echoId: EchoId; text: string }[]> =
  {
    kr: [],
    en: [],
    jp: [],
    zh: [],
  };

for (const cost of Object.values(echoDict)) {
  for (const [echoId, data] of Object.entries(cost)) {
    const id = echoId as EchoId;

    ECHO_CANDIDATES.kr.push({ echoId: id, text: data.kr });
    ECHO_CANDIDATES.en.push({ echoId: id, text: data.en });
    ECHO_CANDIDATES.jp.push({ echoId: id, text: data.jp });
    ECHO_CANDIDATES.zh.push({ echoId: id, text: data.zh });
  }
}

export function getEchoCostKey(cost: number): EchoCostKey | null {
  if (cost === 1) return "Cost1";
  if (cost === 3) return "Cost3";
  if (cost === 4) return "Cost4";
  return null;
}
