import type { AttackType, ElementType } from "./characters";

export interface Stat {
  id: string,
  en: string,
  kr: string,
  jp: string,
  zh: string,
  ValueMain: number[],
  ValueSub: number[],
}

export const FixedStats = {
  dummy: {
    id: "dummy",
    en: "",
    kr: "",
    jp: "",
    zh: "",
    ValueMain: [],
    ValueSub: [],
  },
  hp: {
    id: "hp",
    en: "HP",
    kr: "생명력",
    jp: "HP",
    zh: "生命",
    ValueMain: [0, 0, 0],
    ValueSub: [320, 360, 390, 430, 470, 510, 540, 580],
  },
  hpPct: {
    id: "hpPct",
    en: "HP%",
    kr: "생명력%",
    jp: "HP%",
    zh: "生命%",
    ValueMain: [33.0, 33.0, 33.0],
    ValueSub: [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6,],
  },
  atk: {
    id: "atk",
    en: "Atk",
    kr: "공격력",
    jp: "攻撃力",
    zh: "攻击",
    ValueMain: [0, 0, 0],
    ValueSub: [30, 40, 50, 60],
  },
  atkPct: {
    id: "atkPct",
    en: "Atk%",
    kr: "공격력%",
    jp: "攻撃力%",
    zh: "攻击%",
    ValueMain: [33.0, 30.0, 18.0],
    ValueSub: [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6,],
  },
  def: {
    id: "def",
    en: "Def",
    kr: "방어력",
    jp: "防御力",
    zh: "防御",
    ValueMain: [0, 0, 0],
    ValueSub: [40, 50, 60],
  },
  defPct: {
    id: "defPct",
    en: "Def%",
    kr: "방어력%",
    jp: "防御力%",
    zh: "防御%",
    ValueMain: [41.5, 38.0, 18.0],
    ValueSub: [8.1, 9.0, 10.0, 10.9, 11.8, 12.8, 13.8, 14.7,],
  },
  critRate: {
    id: "critRate",
    en: "Critical Rate",
    kr: "크리티컬",
    jp: "クリティカル",
    zh: "暴击",
    ValueMain: [22.0, 0, 0],
    ValueSub: [6.3, 6.9, 7.5, 8.1, 8.7, 9.3, 9.9, 10.5],
  },
  critDmg: {
    id: "critDmg",
    en: "Critical Damage",
    kr: "크리티컬 피해",
    jp: "クリティカルダメージ",
    zh: "暴击伤害",
    ValueMain: [44.0, 0, 0],
    ValueSub: [12.6, 13.8, 15.0, 16.2, 17.4, 18.6, 19.8, 21.0,],
  },
  healBns: {
    id: "healBns",
    en: "Heal Bonus",
    kr: "치료 효과 보너스",
    jp: "HP回復効果アップ",
    zh: "治療效果加成",
    ValueMain: [26.4, 0, 0],
    ValueSub: [],
  },
  resonanceBns: {
    id: "resonanceBns",
    en: "Resonance Bonus",
    kr: "공명 효율",
    jp: "共鳴効率",
    zh: "共鳴効率",
    ValueMain: [0, 32.0, 0],
    ValueSub: [6.8, 7.6, 8.4, 9.2, 10.0, 10.8, 11.6, 12.4,],
  },
  basicBns: {
    id: "basicBns",
    en: "Basic Attack DMG Bonus",
    kr: "일반공격 피해보너스",
    jp: "通常攻撃ダメージアップ",
    zh: "普攻伤害加成",
    ValueMain: [0, 0, 0],
    ValueSub: [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6,],
  },
  heavyBns: {
    id: "heavyBns",
    en: "Heavy Attack DMG Bonus",
    kr: "강공격 피해보너스",
    jp: "重撃ダメージアップ",
    zh: "重击伤害加成",
    ValueMain: [0, 0, 0],
    ValueSub: [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6,],
  },
  skillBns: {
    id: "skillBns",
    en: "Skill DMG Bonus",
    kr: "공명스킬 피해보너스",
    jp: "共鳴スキルダメージアップ",
    zh: "共鸣技能伤害加成",
    ValueMain: [0, 0, 0],
    ValueSub: [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6,],
  },
  liberationBns: {
    id: "liberationBns",
    en: "Liberation DMG Bonus",
    kr: "공명해방 피해보너스",
    jp: "共鳴解放ダメージアップ",
    zh: "共鸣解放伤害加成",
    ValueMain: [0, 0, 0],
    ValueSub: [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6,],
  },
  glacioBns: {
    id: "glacioBns",
    en: "Glacio DMG Bonus",
    kr: "응결 피해보너스",
    jp: "凝縮ダメージアップ",
    zh: "冷凝伤害加成",
    ValueMain: [0, 30.0, 0],
    ValueSub: [],
  },
  fusionBns: {
    id: "fusionBns",
    en: "Fusion DMG Bonus",
    kr: "융용 피해보너스",
    jp: "焦熱ダメージアップ",
    zh: "热熔伤害加成",
    ValueMain: [0, 30.0, 0],
    ValueSub: [],
  },
  electroBns: {
    id: "electroBns",
    en: "Electro DMG Bonus",
    kr: "전도 피해보너스",
    jp: "電導ダメージアップ",
    zh: "导电伤害加成",
    ValueMain: [0, 30.0, 0],
    ValueSub: [],
  },
  aeroBns: {
    id: "aeroBns",
    en: "Aero DMG Bonus",
    kr: "기류 피해보너스",
    jp: "気動ダメージアップ",
    zh: "氣動傷害加成",
    ValueMain: [0, 30.0, 0],
    ValueSub: [],
  },
  spectroBns: {
    id: "spectroBns",
    en: "Spectro DMG Bonus",
    kr: "회절 피해보너스",
    jp: "回折ダメージアップ",
    zh: "衍射傷害加成",
    ValueMain: [0, 30.0, 0],
    ValueSub: [],
  },
  havocBns: {
    id: "havocBns",
    en: "Havoc DMG Bonus",
    kr: "인멸 피해보너스",
    jp: "消滅ダメージアップ",
    zh: "湮滅傷害加成",
    ValueMain: [0, 30.0, 0],
    ValueSub: [],
  },
  typeBns: {
    id: "typeBns",
    en: "",
    kr: "모든속성 피해보너스",
    jp: "",
    zh: "",
    ValueMain: [0, 0, 0],
    ValueSub: [],
  }
} as const satisfies Record<string, Stat>;

export const ELEMENT_STAT_MAP: Record<ElementType, StatId> = {
  fusion: FixedStats.fusionBns.id,
  glacio: FixedStats.glacioBns.id,
  electro: FixedStats.electroBns.id,
  aero: FixedStats.aeroBns.id,
  spectro: FixedStats.spectroBns.id,
  havoc: FixedStats.havocBns.id,
} as const;

export const ATTACK_TYPE_STAT_MAP: Record<AttackType, StatId> = {
  basic: FixedStats.basicBns.id,
  heavy: FixedStats.heavyBns.id,
  skill: FixedStats.skillBns.id,
  liberation: FixedStats.liberationBns.id,
  heal: FixedStats.healBns.id,
} as const;

export type StatId = (typeof FixedStats)[keyof typeof FixedStats]["id"];
