export const FixedStats = [
  {
    id: "hp",
    en: "Hp",
    kr: "Hp",
    jp: "Hp",
    zh: "Hp",
    ValueMain: [null, null, null],
    ValueSub: [320, 360, 390, 430, 470, 510, 540, 580],
  },
  {
    id: "hpPct",
    en: "Hp%",
    kr: "Hp%",
    jp: "Hp%",
    zh: "Hp%",
    ValueMain: ['33.0%','30.0%','22.8%'],
    SubValue: ['6.4%', '7.1%', '7.9%', '8.6%', '9.4%', '10.1%', '10.9%', '11.6%'],
  },
  {
    id: "atk",
    en: "Atk",
    kr: "공격력",
    jp: "攻撃力",
    zh: "攻撃力",
    ValueMain: [null, null, null],
    SubValue: [30, 40, 50, 60],
  },
  {
    id: "atkPct",
    en: "Atk%",
    kr: "공격력%",
    jp: "攻撃力%",
    zh: "攻撃力%",
    ValueMain: ['33.0%', '30.0%', '18.0%'],
    SubValue: ['6.4%', '7.1%', '7.9%', '8.6%', '9.4%', '10.1%', '10.9%', '11.6%'],
  },
  {
    id: "def",
    en: "",
    kr: "",
    jp: "",
    zh: "",
    ValueMain: [null, null, null],
    SubValue: [40, 50, 60],
  },
  {
    id: "defPct",
    en: "",
    kr: "",
    jp: "",
    zh: "",
    ValueMain: ['41.5%', '38.0%', '18.0%'],
    SubValue: ['8.1%', '9.0%', '10.0%', '10.9%', '11.8%', '12.8%', '13.8%', '14.7%'],
  },
  {
    id: "critRate",
    en: "",
    kr: "크리티컬",
    jp: "",
    zh: "",
    ValueMain: ['22.0%', null, null],
    SubValue: ['6.3%', '6.9%', '7.5%', '8.1%', '8.7%', '9.3%', '9.9%', '10.5%'],
  },
  {
    id: "critDmg",
    en: "",
    kr: "크리티컬 피해",
    jp: "",
    zh: "",
    ValueMain: ['44.0%', null, null],
    SubValue: ['12.6%', '13.8%', '15%', '16.2%', '17.4%', '18.6%', '19.8%', '21%'],
  },
  {
    id: "HealBns",
    en: "",
    kr: "치료 보너스",
    jp: "",
    zh: "",
    ValueMain: ['26.4%', null, null],
    SubValue: null,
  },
  {
    id: "Resonance",
    en: "",
    kr: "공명 효율",
    jp: "",
    zh: "",
    ValueMain: [null, '32.0%', null],
    SubValue: ['6.8%', '7.6%', '8.4%', '9.2%', '10%', '10.8%', '11.6%', '12.4%'],
  },
  {
    id: "",
    en: "",
    kr: "일반공격 피해보너스",
    jp: "",
    zh: "",
    ValueMain: [null, null, null],
    SubValue: ['6.4%', '7.1%', '7.9%', '8.6%', '9.4%', '10.1%', '10.9%', '11.6%'],
  },
  {
    id: "",
    en: "",
    kr: "강공격 피해보너스",
    jp: "",
    zh: "",
    ValueMain: [null, null, null],
    SubValue: ['6.4%', '7.1%', '7.9%', '8.6%', '9.4%', '10.1%', '10.9%', '11.6%'],
  },
  {
    id: "",
    en: "",
    kr: "공명스킬 피해보너스",
    jp: "",
    zh: "",
    ValueMain: [null, null, null],
    SubValue: ['6.4%', '7.1%', '7.9%', '8.6%', '9.4%', '10.1%', '10.9%', '11.6%'],
  },
  {
    id: "",
    en: "",
    kr: "공명해방 피해보너스",
    jp: "",
    zh: "",
    ValueMain: [null, null, null],
    SubValue: ['6.4%', '7.1%', '7.9%', '8.6%', '9.4%', '10.1%', '10.9%', '11.6%'],
  },
  {
    id: "Glacio",
    en: "",
    kr: "응결 피해 보너스",
    jp: "",
    zh: "",
    ValueMain: [null, '30.0%', null],
    SubValue: null,
  },
  {
    id: "Fusion",
    en: "",
    kr: "융용 피해 보너스",
    jp: "",
    zh: "",
    ValueMain: [null, '30.0%', null],
    SubValue: null,
  },
  {
    id: "Electro",
    en: "",
    kr: "전도 피해 보너스",
    jp: "",
    zh: "",
    ValueMain: [null, '30.0%', null],
    SubValue: null,
  },
  {
    id: "Aero",
    en: "",
    kr: "기류 피해 보너스",
    jp: "",
    zh: "",
    ValueMain: [null, '30.0%', null],
    SubValue: null,
  },
  {
    id: "Spectro",
    en: "",
    kr: "회절 피해 보너스",
    jp: "",
    zh: "",
    ValueMain: [null, '30.0%', null],
    SubValue: null,
  },
  {
    id: "Havoc",
    en: "",
    kr: "인멸 피해 보너스",
    jp: "",
    zh: "",
    ValueMain: [null, '30.0%', null],
    SubValue: null,
  },
];
