export const FixedStats = {
  hp: {
    id: "hp",
    en: "HP",
    kr: "HP",
    jp: "HP",
    zh: "生命",
    ValueMain: [null, null, null],
    ValueSub: [320, 360, 390, 430, 470, 510, 540, 580],
  },
  hpPct: {
    id: "hpPct",
    en: "HP%",
    kr: "HP%",
    jp: "HP%",
    zh: "生命%",
    ValueMain: ["33.0%", "30.0%", "22.8%"],
    SubValue: [
      "6.4%",
      "7.1%",
      "7.9%",
      "8.6%",
      "9.4%",
      "10.1%",
      "10.9%",
      "11.6%",
    ],
  },
  atk: {
    id: "atk",
    en: "Atk",
    kr: "공격력",
    jp: "攻撃力",
    zh: "攻击",
    ValueMain: [null, null, null],
    SubValue: [30, 40, 50, 60],
  },
  atkPct: {
    id: "atkPct",
    en: "Atk%",
    kr: "공격력%",
    jp: "攻撃力%",
    zh: "攻击%",
    ValueMain: ["33.0%", "30.0%", "18.0%"],
    SubValue: [
      "6.4%",
      "7.1%",
      "7.9%",
      "8.6%",
      "9.4%",
      "10.1%",
      "10.9%",
      "11.6%",
    ],
  },
  def: {
    id: "def",
    en: "Def",
    kr: "방어력",
    jp: "防御力",
    zh: "防御",
    ValueMain: [null, null, null],
    SubValue: [40, 50, 60],
  },
  defPct: {
    id: "defPct",
    en: "Def%",
    kr: "방어력%",
    jp: "防御力%",
    zh: "防御%",
    ValueMain: ["41.5%", "38.0%", "18.0%"],
    SubValue: [
      "8.1%",
      "9.0%",
      "10.0%",
      "10.9%",
      "11.8%",
      "12.8%",
      "13.8%",
      "14.7%",
    ],
  },
  CritRate: {
    id: "CritRate",
    en: "",
    kr: "크리티컬",
    jp: "クリティカル",
    zh: "暴击",
    ValueMain: ["22.0%", null, null],
    SubValue: ["6.3%", "6.9%", "7.5%", "8.1%", "8.7%", "9.3%", "9.9%", "10.5%"],
  },
  CritDmg: {
    id: "CritDmg",
    en: "",
    kr: "크리티컬 피해",
    jp: "クリティカルダメージ",
    zh: "暴击伤害",
    ValueMain: ["44.0%", null, null],
    SubValue: [
      "12.6%",
      "13.8%",
      "15%",
      "16.2%",
      "17.4%",
      "18.6%",
      "19.8%",
      "21%",
    ],
  },
  healBns: {
    id: "healBns",
    en: "",
    kr: "치료 보너스",
    jp: "HP回復効果アップ",
    zh: "治療效果加成",
    ValueMain: ["26.4%", null, null],
    SubValue: null,
  },
  ResonanceBns: {
    id: "ResonanceBns",
    en: "",
    kr: "공명 효율",
    jp: "共鳴効率",
    zh: "共鳴効率",
    ValueMain: [null, "32.0%", null],
    SubValue: [
      "6.8%",
      "7.6%",
      "8.4%",
      "9.2%",
      "10%",
      "10.8%",
      "11.6%",
      "12.4%",
    ],
  },
  normalBns: {
    id: "normalBns",
    en: "",
    kr: "일반공격 피해보너스",
    jp: "通常攻撃ダメージアップ",
    zh: "普攻伤害加成",
    ValueMain: [null, null, null],
    SubValue: [
      "6.4%",
      "7.1%",
      "7.9%",
      "8.6%",
      "9.4%",
      "10.1%",
      "10.9%",
      "11.6%",
    ],
  },
  heavyBns: {
    id: "heavyBns",
    en: "",
    kr: "강공격 피해보너스",
    jp: "重撃ダメージアップ",
    zh: "重击伤害加成",
    ValueMain: [null, null, null],
    SubValue: [
      "6.4%",
      "7.1%",
      "7.9%",
      "8.6%",
      "9.4%",
      "10.1%",
      "10.9%",
      "11.6%",
    ],
  },
  skillBns: {
    id: "skillBns",
    en: "",
    kr: "공명스킬 피해보너스",
    jp: "共鳴スキルダメージアップ",
    zh: "共鸣技能伤害加成",
    ValueMain: [null, null, null],
    SubValue: [
      "6.4%",
      "7.1%",
      "7.9%",
      "8.6%",
      "9.4%",
      "10.1%",
      "10.9%",
      "11.6%",
    ],
  },
  ultBns: {
    id: "ultBns",
    en: "",
    kr: "공명해방 피해보너스",
    jp: "共鳴解放ダメージアップ",
    zh: "共鸣解放伤害加成",
    ValueMain: [null, null, null],
    SubValue: [
      "6.4%",
      "7.1%",
      "7.9%",
      "8.6%",
      "9.4%",
      "10.1%",
      "10.9%",
      "11.6%",
    ],
  },
  GlacioBns: {
    id: "GlacioBns",
    en: "",
    kr: "응결 피해 보너스",
    jp: "凝縮ダメージアップ",
    zh: "冷凝伤害加成",
    ValueMain: [null, "30.0%", null],
    SubValue: null,
  },
  FusionBns: {
    id: "FusionBns",
    en: "",
    kr: "융용 피해 보너스",
    jp: "焦熱ダメージアップ",
    zh: "热熔伤害加成",
    ValueMain: [null, "30.0%", null],
    SubValue: null,
  },
  ElectroBns: {
    id: "ElectroBns",
    en: "",
    kr: "전도 피해 보너스",
    jp: "電導ダメージアップ",
    zh: "导电伤害加成",
    ValueMain: [null, "30.0%", null],
    SubValue: null,
  },
  AeroBns: {
    id: "AeroBns",
    en: "",
    kr: "기류 피해 보너스",
    jp: "気動ダメージアップ",
    zh: "氣動傷害加成",
    ValueMain: [null, "30.0%", null],
    SubValue: null,
  },
  SpectroBns: {
    id: "SpectroBns",
    en: "",
    kr: "회절 피해 보너스",
    jp: "回折ダメージアップ",
    zh: "衍射傷害加成",
    ValueMain: [null, "30.0%", null],
    SubValue: null,
  },
  HavocBns: {
    id: "HavocBns",
    en: "",
    kr: "인멸 피해 보너스",
    jp: "消滅ダメージアップ",
    zh: "湮滅傷害加成",
    ValueMain: [null, "30.0%", null],
    SubValue: null,
  },
};

export const FixedStatsMain4 = Object.fromEntries(
  Object.entries(FixedStats).filter(([_, stat]) => stat.ValueMain?.[0] !== null)
);

export const FixedStatsMain3 = Object.fromEntries(
  Object.entries(FixedStats).filter(([_, stat]) => stat.ValueMain?.[1] !== null)
);

export const FixedStatsMain1 = Object.fromEntries(
  Object.entries(FixedStats).filter(([_, stat]) => stat.ValueMain?.[2] !== null)
);

export const FixedStatsSub = Object.fromEntries(
  Object.entries(FixedStats).filter(([_, stat]) => stat.SubValue !== null)
);

export const FixedMainSub = {
  
}
