export const weapon = {
  StraightSword: [
    {
      id: "Emerald of Genesis",
      kr: "천년의 회류",
      jp: "千古の湖水",
      zh: "千古洑流",
      imgKey: "ico001",
    },
    {
      id: "Blazing Brilliance",
      kr: "솟아오르는 화염",
      jp: "赫く燃ゆる流光",
      zh: "赫奕流明",
      imgKey: "ico002",
    },
    {
      id: "Red Spring",
      kr: "날카로운 봄",
      jp: "春裁ち",
      zh: "裁春",
      imgKey: "ico003",
    },
    {
      id: "Unflickering Valor",
      kr: "흔들리지 않는 용기",
      jp: "エンドレスボヤージュ",
      zh: "不灭航路",
      imgKey: "ico004",
    },
    {
      id: "Bloodpact's Pledge",
      kr: "혈맹의 약속",
      jp: "血の盟約",
      zh: "血誓盟约",
      imgKey: "ico005",
    },
    {
      id: "Somnoire Anchor",
      kr: "마음의 닻",
      jp: "心の錨",
      zh: "心之锚",
      imgKey: "ico101",
    },
    {
      id: "Overture",
      kr: "행진의 서곡",
      jp: "行進オーバーチュア",
      zh: "行进序曲",
      imgKey: "ico102",
    },
    {
      id: "Sword#18",
      kr: "18형 직검 · 순간의 칼빛",
      jp: "瞬斬刀＃18",
      zh: "瞬斩刀-18型",
      imgKey: "ico103",
    },
    {
      id: "Commando of Conviction",
      kr: "야귀의 신념",
      jp: "決死の一人戦",
      zh: "不归孤军",
      imgKey: "ico104",
    },
    {
      id: "Lunar Cutter",
      kr: "상승의 서녘",
      jp: "倒錯の星",
      zh: "西升",
      imgKey: "ico105",
    },
    {
      id: "Lumingloss",
      kr: "천공의 광경",
      jp: "万象変遷",
      zh: "飞景",
      imgKey: "ico106",
    },
    {
      id: "Endless Collapse",
      kr: "영원의 붕괴",
      jp: "永遠を砕く重力崩壊",
      zh: "永续坍缩",
      imgKey: "ico107",
    },
    {
      id: "Fables of Wisdom",
      kr: "풍류의 우화시",
      jp: "風刺のファブリオー",
      zh: "风流的寓言诗",
      imgKey: "ico108",
    },
  ],
  GreatSword: [
    {
      id: "Lutrous Razor",
      kr: "푸른 물결의 빛",
      jp: "仙境の湖光",
      zh: "浩境粼光",
      imgKey: "ico001",
    },
    {
      id: "Verdant Summit",
      kr: "청룡의 천장",
      jp: "蒼鱗連峰",
      zh: "苍鳞千嶂",
      imgKey: "ico002",
    },
    {
      id: "Ages of Harvest",
      kr: "태평성대",
      jp: "歳華調和",
      zh: "时和岁稔",
      imgKey: "ico003",
    },
    {
      id: "Discord",
      kr: "기묘한 울림",
      jp: "霊感ディスコード",
      zh: "异响空灵",
      imgKey: "ico101",
    },
    {
      id: "Broadblade#41",
      kr: "41형 대검 · 무거운 책임",
      jp: "重破刃＃41",
      zh: "重破刃-41型",
      imgKey: "ico102",
    },
    {
      id: "Dauntless Evernight",
      kr: "장야의 불빛",
      jp: "長夜の灯火",
      zh: "永夜长明",
      imgKey: "ico103",
    },
    {
      id: "Helios Cleaver",
      kr: "저무는 동녘",
      jp: "逆行の星",
      zh: "东落",
      imgKey: "ico104",
    },
    {
      id: "Autumntrace",
      kr: "가을의 무늬",
      jp: "秋の名残",
      zh: "纹秋",
      imgKey: "ico105",
    },
    {
      id: "Waning Redshift",
      kr: "멸망의 주파수",
      jp: "破滅に迫る赤方偏移",
      zh: "凋亡频移",
      imgKey: "ico106",
    },
    {
      id: "Meditations on Mercy",
      kr: "용서의 명상록",
      jp: "寛恕のタ・エイス・ヘアウトン",
      zh: "容赦的沉思录",
      imgKey: "ico107",
    },
  ],
  Gauntlet: [
    {
      id: "Abyss Surges",
      kr: "물결의 파동",
      jp: "怒涛の湖音",
      zh: "擎渊怒涛",
      imgKey: "ico001",
    },
    {
      id: "Verity's Handle",
      kr: "팔방의 천추",
      jp: "万端の枢機",
      zh: "诸方玄枢",
      imgKey: "ico002",
    },
    {
      id: "Tragicomedy",
      kr: "희비극",
      jp: "トラジコメーディア",
      zh: "悲喜剧",
      imgKey: "ico003",
    },
    {
      id: "Blazing Justice",
      kr: "불빛의 심판",
      jp: "焔光の裁き",
      zh: "焰光裁定",
      imgKey: "ico004",
    },
    {
      id: "Marcato",
      kr: "바람의 악센트",
      jp: "狂乱マルカート",
      zh: "呼啸重音",
      imgKey: "ico101",
    },
    {
      id: "Gauntlets#21D",
      kr: "21형 권갑 · 아이언 팬텀",
      jp: "鋼影拳＃21・四番",
      zh: "钢影拳-21丁型",
      imgKey: "ico102",
    },
    {
      id: "Amity Accord",
      kr: "전우의 의리",
      jp: "金鉄の志",
      zh: "袍泽之固",
      imgKey: "ico103",
    },
    {
      id: "Hollow Mirage",
      kr: "천공의 역행",
      jp: "驚異の星",
      zh: "骇行",
      imgKey: "ico104",
    },
    {
      id: "Stonard",
      kr: "황금 권갑",
      jp: "黄金の拳",
      zh: "金掌",
      imgKey: "ico105",
    },
    {
      id: "Celestial Spiral",
      kr: "천상의 나선",
      jp: "星屑が捩れる渦巻腕",
      zh: "尘云旋臂",
      imgKey: "ico106",
    },
    {
      id: "Legend of Drunken Hero",
      kr: "만취의 영웅지",
      jp: "酩酊のエポス",
      zh: "酩酊的英雄志",
      imgKey: "ico107",
    }
  ],
  Firearm: [],
  Amplifter: [],
};

export const weaponStats = {};
