export const weapon = {
  //$ Count: 13
  StraightSword: [
    {
      id: "Emerald of Genesis",
      kr: "천년의 회류",
      jp: "千古の湖水",
      zh: "千古洑流",
      imgKey: "ico001",
    },
    {
      id: "Blazing Brilliance",
      kr: "솟아오르는 화염",
      jp: "赫く燃ゆる流光",
      zh: "赫奕流明",
      imgKey: "ico002",
    },
    {
      id: "Red Spring",
      kr: "날카로운 봄",
      jp: "春裁ち",
      zh: "裁春",
      imgKey: "ico003",
    },
    {
      id: "Unflickering Valor",
      kr: "흔들리지 않는 용기",
      jp: "エンドレスボヤージュ",
      zh: "不灭航路",
      imgKey: "ico004",
    },
    {
      id: "Bloodpact's Pledge",
      kr: "혈맹의 약속",
      jp: "血の盟約",
      zh: "血誓盟约",
      imgKey: "ico005",
    },
    {
      id: "Somnoire Anchor",
      kr: "마음의 닻",
      jp: "心の錨",
      zh: "心之锚",
      imgKey: "ico101",
    },
    {
      id: "Overture",
      kr: "행진의 서곡",
      jp: "行進オーバーチュア",
      zh: "行进序曲",
      imgKey: "ico102",
    },
    {
      id: "Sword#18",
      kr: "18형 직검 · 순간의 칼빛",
      jp: "瞬斬刀＃18",
      zh: "瞬斩刀-18型",
      imgKey: "ico103",
    },
    {
      id: "Commando of Conviction",
      kr: "야귀의 신념",
      jp: "決死の一人戦",
      zh: "不归孤军",
      imgKey: "ico104",
    },
    {
      id: "Lunar Cutter",
      kr: "상승의 서녘",
      jp: "倒錯の星",
      zh: "西升",
      imgKey: "ico105",
    },
    {
      id: "Lumingloss",
      kr: "천공의 광경",
      jp: "万象変遷",
      zh: "飞景",
      imgKey: "ico106",
    },
    {
      id: "Endless Collapse",
      kr: "영원의 붕괴",
      jp: "永遠を砕く重力崩壊",
      zh: "永续坍缩",
      imgKey: "ico107",
    },
    {
      id: "Fables of Wisdom",
      kr: "풍류의 우화시",
      jp: "風刺のファブリオー",
      zh: "风流的寓言诗",
      imgKey: "ico108",
    },
  ],
  //$ Count: 10
  GreatSword: [
    {
      id: "Lutrous Razor",
      kr: "푸른 물결의 빛",
      jp: "仙境の湖光",
      zh: "浩境粼光",
      imgKey: "ico001",
    },
    {
      id: "Verdant Summit",
      kr: "청룡의 천장",
      jp: "蒼鱗連峰",
      zh: "苍鳞千嶂",
      imgKey: "ico002",
    },
    {
      id: "Ages of Harvest",
      kr: "태평성대",
      jp: "歳華調和",
      zh: "时和岁稔",
      imgKey: "ico003",
    },
    {
      id: "Discord",
      kr: "기묘한 울림",
      jp: "霊感ディスコード",
      zh: "异响空灵",
      imgKey: "ico101",
    },
    {
      id: "Broadblade#41",
      kr: "41형 대검 · 무거운 책임",
      jp: "重破刃＃41",
      zh: "重破刃-41型",
      imgKey: "ico102",
    },
    {
      id: "Dauntless Evernight",
      kr: "장야의 불빛",
      jp: "長夜の灯火",
      zh: "永夜长明",
      imgKey: "ico103",
    },
    {
      id: "Helios Cleaver",
      kr: "저무는 동녘",
      jp: "逆行の星",
      zh: "东落",
      imgKey: "ico104",
    },
    {
      id: "Autumntrace",
      kr: "가을의 무늬",
      jp: "秋の名残",
      zh: "纹秋",
      imgKey: "ico105",
    },
    {
      id: "Waning Redshift",
      kr: "멸망의 주파수",
      jp: "破滅に迫る赤方偏移",
      zh: "凋亡频移",
      imgKey: "ico106",
    },
    {
      id: "Meditations on Mercy",
      kr: "용서의 명상록",
      jp: "寛恕のタ・エイス・ヘアウトン",
      zh: "容赦的沉思录",
      imgKey: "ico107",
    },
  ],
  //$ Count: 11
  Gauntlet: [
    {
      id: "Abyss Surges",
      kr: "물결의 파동",
      jp: "怒涛の湖音",
      zh: "擎渊怒涛",
      imgKey: "ico001",
    },
    {
      id: "Verity's Handle",
      kr: "팔방의 천추",
      jp: "万端の枢機",
      zh: "诸方玄枢",
      imgKey: "ico002",
    },
    {
      id: "Tragicomedy",
      kr: "희비극",
      jp: "トラジコメーディア",
      zh: "悲喜剧",
      imgKey: "ico003",
    },
    {
      id: "Blazing Justice",
      kr: "불빛의 심판",
      jp: "焔光の裁き",
      zh: "焰光裁定",
      imgKey: "ico004",
    },
    {
      id: "Marcato",
      kr: "바람의 악센트",
      jp: "狂乱マルカート",
      zh: "呼啸重音",
      imgKey: "ico101",
    },
    {
      id: "Gauntlets#21D",
      kr: "21형 권갑 · 아이언 팬텀",
      jp: "鋼影拳＃21・四番",
      zh: "钢影拳-21丁型",
      imgKey: "ico102",
    },
    {
      id: "Amity Accord",
      kr: "전우의 의리",
      jp: "金鉄の志",
      zh: "袍泽之固",
      imgKey: "ico103",
    },
    {
      id: "Hollow Mirage",
      kr: "천공의 역행",
      jp: "驚異の星",
      zh: "骇行",
      imgKey: "ico104",
    },
    {
      id: "Stonard",
      kr: "황금 권갑",
      jp: "黄金の拳",
      zh: "金掌",
      imgKey: "ico105",
    },
    {
      id: "Celestial Spiral",
      kr: "천상의 나선",
      jp: "星屑が捩れる渦巻腕",
      zh: "尘云旋臂",
      imgKey: "ico106",
    },
    {
      id: "Legend of Drunken Hero",
      kr: "만취의 영웅지",
      jp: "酩酊のエポス",
      zh: "酩酊的英雄志",
      imgKey: "ico107",
    },
  ],
  //$ Count: 10
  Firearm: [
    {
      id: "Static Mist",
      kr: "부동의 안개",
      jp: "不変の湖煙",
      zh: "停驻之烟",
      imgKey: "ico001",
    },
    {
      id: "The Last Dance",
      kr: "죽음과 춤",
      jp: "ラストダンス",
      zh: "死与舞",
      imgKey: "ico002",
    },
    {
      id: "Woodland Aria",
      kr: "숲속의 아리아",
      jp: "森のアリア",
      zh: "林间的咏叹调",
      imgKey: "ico003",
    },
    {
      id: "Cadenza",
      kr: "화려한 악곡",
      jp: "華麗カテンツァ",
      zh: "华彩乐段",
      imgKey: "ico101",
    },
    {
      id: "Pistols#26",
      kr: "26형 권총 · 맹렬한 돌격",
      jp: "穿撃銃＃26",
      zh: "穿击枪-26型",
      imgKey: "ico102",
    },
    {
      id: "Undying Flame",
      kr: "불멸의 성화",
      jp: "燃え尽きぬ焔",
      zh: "无眠烈火",
      imgKey: "ico103",
    },
    {
      id: "Novaburst",
      kr: "천공의 순간",
      jp: "疾走の星",
      zh: "飞逝",
      imgKey: "ico104",
    },
    {
      id: "Thunderbolt",
      kr: "뇌전",
      jp: "迸る雷霆",
      zh: "奔雷",
      imgKey: "ico105",
    },
    {
      id: "Relativistic Jet",
      kr: "역설의 격류",
      jp: "悖理を説く宇宙ジェット",
      zh: "悖论喷流",
      imgKey: "ico106",
    },
    {
      id: "Romance in Farewell",
      kr: "작별의 로맨스",
      jp: "別れのメロス",
      zh: "叙别的罗曼史",
      imgKey: "ico107",
    },
  ],
  //$ Count: 15
  Amplifter: [
    {
      id: "Cosmic Ripples",
      kr: "파도의 기록",
      jp: "栄枯の湖岸",
      zh: "漪澜浮录",
      imgKey: "ico001",
    },
    {
      id: "Stringmaster",
      kr: "꼭두각시의 손",
      jp: "糸繰りの奇術",
      zh: "掣傀之手",
      imgKey: "ico002",
    },
    {
      id: "Rime-Draped Sprouts",
      kr: "옥수 비단",
      jp: "氷華の雅印",
      zh: "琼枝冰绡",
      imgKey: "ico003",
    },
    {
      id: "Stellar Symphony",
      kr: "뭇별의 교향곡",
      jp: "星々のコンチェルト",
      zh: "星序协响",
      imgKey: "ico004",
    },
    {
      id: "Luminous Hymn",
      kr: "광휘의 찬송가",
      jp: "光のハルモニア",
      zh: "和光回唱",
      imgKey: "ico005",
    },
    {
      id: "Whispers of Sirens",
      kr: "바다의 속삭임",
      jp: "深海の囁き",
      zh: "海的呢喃",
      imgKey: "ico006",
    },
    {
      id: "Call of the Abyss",
      kr: "심해의 메아리",
      jp: "海淵のリフレイン",
      zh: "渊海回声",
      imgKey: "ico101",
    },
    {
      id: "Variation",
      kr: "판타지 변주",
      jp: "奇妙バリエーション",
      zh: "奇幻变奏",
      imgKey: "ico102",
    },
    {
      id: "Ocean's Gift",
      kr: "바다의 선물",
      jp: "海の恩恵",
      zh: "大海的馈赠",
      imgKey: "ico103",
    },
    {
      id: "Rectifier#25",
      kr: "25형 증폭기 · 울림의 멜로디",
      jp: "鳴動機＃25",
      zh: "鸣动仪-25型",
      imgKey: "ico104",
    },
    {
      id: "Jinzhou Keeper",
      kr: "금주의 수호",
      jp: "今州の衛士",
      zh: "今州守望",
      imgKey: "ico105",
    },
    {
      id: "Comet Flare",
      kr: "굉음",
      jp: "変化の星",
      zh: "异度",
      imgKey: "ico106",
    },
    {
      id: "Augment",
      kr: "청음",
      jp: "清らかな音",
      zh: "清音",
      imgKey: "ico107",
    },
    {
      id: "Fusion Accretion",
      kr: "융합의 원반",
      jp: "コアが溶融する降着円盤",
      zh: "核熔星盘",
      imgKey: "ico108",
    },
    {
      id: "Waltz in Masquerade",
      kr: "허위의 왈츠",
      jp: "虚飾のワルツ",
      zh: "虚饰的华尔兹",
      imgKey: "ico109",
    },
  ],
};
export const weaponStat = {
  //#region StraightSword
  "Emerald of Genesis": {
    atk: 588,
    value: [24.3, 12.8],
    statType: ["critRate", "ResonanceBns"],
  },
  "Blazing Brilliance": {
    atk: 588,
    value: [48.6, 12],
    statType: ["critDmg", "atkPct"],
  },
  "Red Spring": {
    atk: 588,
    value: [24.3, 12],
    statType: ["critRate", "atkPct"],
  },
  "Unflickering Valor": {
    atk: 413,
    value: [77, 8],
    statType: ["ResonanceBns", "critRate"],
  },
  "Bloodpact's Pledge": {
    atk: 588,
    value: [38.9, 0],
    statType: ["ResonanceBns", "atk"],
  },
  "Somnoire Anchor": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  Overture: {
    atk: 338,
    value: [51.8, 0],
    statType: ["ResonanceBns", "atk"],
  },
  "Sword#18": {
    atk: 388,
    value: [36.5, 0],
    statType: ["atkPct", "atk"],
  },
  "Commando of Conviction": {
    atk: 413,
    value: [30.4, 0],
    statType: ["atkPct", "atk"],
  },
  "Lunar Cutter": {
    atk: 413,
    value: [30.4, 0],
    statType: ["atkPct", "atk"],
  },
  Lumingloss: {
    atk: 388,
    value: [36.5, 0],
    statType: ["atkPct", "atk"],
  },
  "Endless Collapse": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  "Fables of Wisdom": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  //#endregion

  //#region GreatSword
  "Lutrous Razor": {
    atk: 588,
    value: [36.5, 12.8],
    statType: ["atkPct", "ResonanceBns"],
  },
  "Verdant Summit": {
    atk: 588,
    value: [48.6, 12],
    statType: ["critDmg", "typeBns"],
  },
  "Ages of Harvest": {
    atk: 588,
    value: [24.3, 12],
    statType: ["critRate", "typeBns"],
  },
  Discord: {
    atk: 338,
    value: [51.8, 0],
    statType: ["ResonanceBns", "atk"],
  },
  "Broadblade#41": {
    atk: 413,
    value: [32.4, 0],
    statType: ["ResonanceBns", "atk"],
  },
  "Dauntless Evernight": {
    atk: 338,
    value: [61.6, 0],
    statType: ["defPct", "atk"],
  },
  "Helios Cleaver": {
    atk: 413,
    value: [30.4, 0],
    statType: ["atkPct", "atk"],
  },
  Autumntrace: {
    atk: 413,
    value: [20.3, 0],
    statType: ["critRate", "atk"],
  },
  "Waning Redshift": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  "Meditations on Mercy": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  //#endregion

  //#region Gauntlet
  "Abyss Surges": {
    atk: 588,
    value: [36.5, 12.8],
    statType: ["atkPct", "ResonanceBns"],
  },
  "Verity's Handle": {
    atk: 588,
    value: [24.3, 12],
    statType: ["critRate", "typeBns"],
  },
  Tragicomedy: {
    atk: 588,
    value: [24.3, 12],
    statType: ["critRate", "atkPct"],
  },
  "Blazing Justice": {
    atk: 588,
    value: [48.6, 12],
    statType: ["critDmg", "atkPct"],
  },
  Marcato: {
    atk: 338,
    value: [51.8, 0],
    statType: ["ResonanceBns", "atk"],
  },
  "Gauntlets#21D": {
    atk: 388,
    value: [38.9, 0],
    statType: ["ResonanceBns", "atk"],
  },
  "Amity Accord": {
    atk: 338,
    value: [61.6, 0],
    statType: ["defPct", "atk"],
  },
  "Hollow Mirage": {
    atk: 413,
    value: [30.4, 0],
    statType: ["atkPct", "atk"],
  },
  Stonard: {
    atk: 413,
    value: [20.3, 0],
    statType: ["critRate", "atk"],
  },
  "Celestial Spiral": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  "Legend of Drunken Hero": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  //#endregion

  //#region Firearm
  "Static Mist": {
    atk: 588,
    value: [24.3, 12.8],
    statType: ["critRate", "ResonanceBns"],
  },
  "The Last Dance": {
    atk: 500,
    value: [72, 12],
    statType: ["critDmg", "atkPct"],
  },
  "Woodland Aria": {
    atk: 500,
    value: [36, 12],
    statType: ["critRate", "atkPct"],
  },
  Cadenza: {
    atk: 338,
    value: [51.8, 0],
    statType: ["ResonanceBns", "atk"],
  },
  "Pistols#26": {
    atk: 388,
    value: [36.5, 0],
    statType: ["atkPct", "atk"],
  },
  "Undying Flame": {
    atk: 413,
    value: [30.4, 0],
    statType: ["atkPct", "atk"],
  },
  Novaburst: {
    atk: 413,
    value: [30.4, 0],
    statType: ["atkPct", "atk"],
  },
  Thunderbolt: {
    atk: 388,
    value: [36.5, 0],
    statType: ["atkPct", "atk"],
  },
  "Relativistic Jet": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  "Romance in Farewell": {
    atk: 463,
    value: [18.2, 0],
    statType: ["aktPct", "atk"],
  },
  //#endregion

  //#region Amplifter
  "Cosmic Ripples": {
    atk: 500,
    value: [54, 12.8],
    statType: ["atkPct", "ResonanceBns"],
  },
  Stringmaster: {
    atk: 500,
    value: [36, 12],
    statType: ["critRate", "typeBns"],
  },
  "Rime-Draped Sprouts": {
    atk: 500,
    value: [72, 12],
    statType: ["critDmg", "atkPct"],
  },
  "Stellar Symphony": {
    atk: 413,
    value: [77, 12],
    statType: ["ResonanceBns", "hpPct"],
  },
  "Luminous Hymn": {
    atk: 500,
    value: [36, 12],
    statType: ["critRate", "atkPct"],
  },
  "Whispers of Sirens": {
    atk: 500,
    value: [72, 12],
    statType: ["critDmg", "atkPct"],
  },
  "Call of the Abyss": {
    atk: 338,
    value: [51.8, 0],
    statType: ["ResonanceBns", "atk"],
  },
  Variation: {
    atk: 338,
    value: [51.8, 0],
    statType: ["ResonanceBns", "atk"],
  },
  "Ocean's Gift": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  "Rectifier#25": {
    atk: 338,
    value: [51.8, 0],
    statType: ["ResonanceBns", "atk"],
  },
  "Jinzhou Keeper": {
    atk: 388,
    value: [36.5, 0],
    statType: ["aktPct", "atk"],
  },
  "Comet Flare": {
    atk: 413,
    value: [30.4, 0],
    statType: ["hpPct", "atk"],
  },
  Augment: {
    atk: 413,
    value: [20.3, 0],
    statType: ["critRate", "atk"],
  },
  "Fusion Accretion": {
    atk: 463,
    value: [18.2, 0],
    statType: ["atkPct", "atk"],
  },
  "Waltz in Masquerade": {
    atk: 463,
    value: [, 0],
    statType: ["", ""],
  }
  //#endregion
};
