import { type WeaponType } from "./characters";
import type { weaponStat } from "./weaponStats";

export type WeaponId = keyof typeof weaponStat

export interface Weapon {
    id: WeaponId,
    en: string,
    kr: string,
    jp: string,
    zh: string,
    imgKey: string,
}

export const weapon = {
  sword: { //* 직검
    //$ 5-Starts
    sword001: {
			id: "sword001",
      en: "Emerald of Genesis",
      kr: "천년의 회류",
      jp: "千古の湖水",
      zh: "千古洑流",
      imgKey: "ico001",
    },
    sword002:{
			id: "sword002",
      en: "Blazing Brilliance",
      kr: "솟아오르는 화염",
      jp: "赫く燃ゆる流光",
      zh: "赫奕流明",
      imgKey: "ico002",
    },
    sword003:{
			id: "sword003",
      en: "Red Spring",
      kr: "날카로운 봄",
      jp: "春裁ち",
      zh: "裁春",
      imgKey: "ico003",
    },
    sword004:{
			id: "sword004",
      en: "Unflickering Valor",
      kr: "흔들리지 않는 용기",
      jp: "エンドレスボヤージュ",
      zh: "不灭航路",
      imgKey: "ico004",
    },
    sword005:{
			id: "sword005",
      en: "Bloodpact's Pledge",
      kr: "혈맹의 약속",
      jp: "血の盟約",
      zh: "血誓盟约",
      imgKey: "ico005",
    },
    sword006:{
			id: "sword006",
      en: "Defier's Thorn",
      kr: "숙명에 맞서는 관",
      jp: "定めを覆す荊冠",
      zh: "不屈命定之冠",
      imgKey: "ico006",
    },
    sword007:{
			id: "sword007",
      en: "Emerald Sentence",
      kr: "푸른 의지",
      jp: "破敵の鋭竹",
      zh: "裁竹",
      imgKey: "ico007",
    },
    sword008:{ //* 신상시
			id: "sword008",
      en: "Laser Shearer",
      kr: "레이저 변형",
      jp: "レーザーの鋭剣",
      zh: "镭射切变",
      imgKey: "ico008",
    },
    sword009:{ //* 에이메스
			id: "sword009",
      en: "Everbright Polestar",
      kr: "영원한 샛별",
      jp: "とこしえの明星",
      zh: "永远的启明星",
      imgKey: "ico009",
    },
    //$ 4-Starts
    sword101:{
			id: "sword101",
      en: "Somnoire Anchor",
      kr: "마음의 닻",
      jp: "心の錨",
      zh: "心之锚",
      imgKey: "ico101",
    },
    sword102:{
			id: "sword102",
      en: "Overture",
      kr: "행진의 서곡",
      jp: "行進オーバーチュア",
      zh: "行进序曲",
      imgKey: "ico102",
    },
    sword103:{
			id: "sword103",
      en: "Sword#18",
      kr: "18형 직검 · 순간의 칼빛",
      jp: "瞬斬刀＃18",
      zh: "瞬斩刀-18型",
      imgKey: "ico103",
    },
    sword104:{
			id: "sword104",
      en: "Commando of Conviction",
      kr: "야귀의 신념",
      jp: "決死の一人戦",
      zh: "不归孤军",
      imgKey: "ico104",
    },
    sword105:{
			id: "sword105",
      en: "Lunar Cutter",
      kr: "상승의 서녘",
      jp: "倒錯の星",
      zh: "西升",
      imgKey: "ico105",
    },
    sword106:{
			id: "sword106",
      en: "Lumingloss",
      kr: "천공의 광경",
      jp: "万象変遷",
      zh: "飞景",
      imgKey: "ico106",
    },
    sword107:{
			id: "sword107",
      en: "Endless Collapse",
      kr: "영원의 붕괴",
      jp: "永遠を砕く重力崩壊",
      zh: "永续坍缩",
      imgKey: "ico107",
    },
    sword108:{
			id: "sword108",
      en: "Fables of Wisdom",
      kr: "풍류의 우화시",
      jp: "風刺のファブリオー",
      zh: "风流的寓言诗",
      imgKey: "ico108",
    },
    sword109:{
			id: "sword109",
      en: "Feather Edge",
      kr: "예리한 날개깃",
      jp: "鋭利な翼",
      zh: "翼锋",
      imgKey: "ico109",
    },
  },
  broadblade: { //* 대검
    //$ 5-Starts
    broadblade001:{
			id: "broadblade001",
      en: "Lutrous Razor",
      kr: "푸른 물결의 빛",
      jp: "仙境の湖光",
      zh: "浩境粼光",
      imgKey: "ico001",
    },
    broadblade002:{
			id: "broadblade002",
      en: "Verdant Summit",
      kr: "청룡의 천장",
      jp: "蒼鱗連峰",
      zh: "苍鳞千嶂",
      imgKey: "ico002",
    },
    broadblade003:{
			id: "broadblade003",
      en: "Ages of Harvest",
      kr: "태평성대",
      jp: "歳華調和",
      zh: "时和岁稔",
      imgKey: "ico003",
    },
    broadblade004:{ 
			id: "broadblade004",
      en: "Wildfire Mark",
      kr: "불길",
      jp: "闘炎の爪痕",
      zh: "焰痕",
      imgKey: "ico004",
    },
    broadblade005:{
			id: "broadblade005",
      en: "Thunderflare Dominion",
      kr: "천둥벼락을 다스리는 권능",
      jp: "雷霆を統べし王剣",
      zh: "驭冕铸雷之权",
      imgKey: "ico005",
    },
    broadblade006:{ //* 신상시
			id: "broadblade006",
      en: "Radiance Cleaver",
      kr: "에너지 절단",
      jp: "ラディアンスの切っ先",
      zh: "源能机锋",
      imgKey: "ico007",
    },
    broadblade007:{ //* 치사
			id: "broadblade007",
      en: "Kumokiri",
      kr: "쿠모키리",
      jp: "曇斬",
      zh: "昙切",
      imgKey: "ico006",
    },
    broadblade008:{ //* 모니에
			id: "broadblade008",
      en: "Starfield Calibrator",
      kr: "별하늘 연산 측정기",
      jp: "スターキャリブレーター",
      zh: "宙算仪轨",
      imgKey: "ico008",
    },
    //$ 4-Starts
    broadblade101:{
			id: "broadblade101",
      en: "Discord",
      kr: "기묘한 울림",
      jp: "霊感ディスコード",
      zh: "异响空灵",
      imgKey: "ico101",
    },
    broadblade102:{
			id: "broadblade102",
      en: "Broadblade#41",
      kr: "41형 대검 · 무거운 책임",
      jp: "重破刃＃41",
      zh: "重破刃-41型",
      imgKey: "ico102",
    },
    broadblade103:{
			id: "broadblade103",
      en: "Dauntless Evernight",
      kr: "장야의 불빛",
      jp: "長夜の灯火",
      zh: "永夜长明",
      imgKey: "ico103",
    },
    broadblade104:{
			id: "broadblade104",
      en: "Helios Cleaver",
      kr: "저무는 동녘",
      jp: "逆行の星",
      zh: "东落",
      imgKey: "ico104",
    },
    broadblade105:{
			id: "broadblade105",
      en: "Autumntrace",
      kr: "가을의 무늬",
      jp: "秋の名残",
      zh: "纹秋",
      imgKey: "ico105",
    },
    broadblade106:{
			id: "broadblade106",
      en: "Waning Redshift",
      kr: "멸망의 주파수",
      jp: "破滅に迫る赤方偏移",
      zh: "凋亡频移",
      imgKey: "ico106",
    },
    broadblade107:{
			id: "broadblade107",
      en: "Meditations on Mercy",
      kr: "용서의 명상록",
      jp: "寛恕のタ・エイス・ヘアウトン",
      zh: "容赦的沉思录",
      imgKey: "ico107",
    },
    broadblade108:{
			id: "broadblade108",
      en: "Aureate Zenith",
      kr: "금빛 하늘",
      jp: "金の天穹",
      zh: "金穹",
      imgKey: "ico108",
    },
  },
  gauntlet: { //* 권갑
    //$ 5-Starts
    gauntlet001:{
			id: "gauntlet001",
      en: "Abyss Surges",
      kr: "물결의 파동",
      jp: "怒涛の湖音",
      zh: "擎渊怒涛",
      imgKey: "ico001",
    },
    gauntlet002:{
			id: "gauntlet002",
      en: "Verity's Handle",
      kr: "팔방의 천추",
      jp: "万端の枢機",
      zh: "诸方玄枢",
      imgKey: "ico002",
    },
    gauntlet003:{
			id: "gauntlet003",
      en: "Tragicomedy",
      kr: "희비극",
      jp: "トラジコメーディア",
      zh: "悲喜剧",
      imgKey: "ico003",
    },
    gauntlet004:{
			id: "gauntlet004",
      en: "Blazing Justice",
      kr: "불빛의 심판",
      jp: "焔光の裁き",
      zh: "焰光裁定",
      imgKey: "ico004",
    },
    gauntlet005:{
			id: "gauntlet005",
      en: "Moongazer's Sigil",
      kr: "세상 만물의 진리",
      jp: "万物持存的注释",
      zh: "万物持存的注释",
      imgKey: "ico005",
    },
    gauntlet006:{ //* 신상시
			id: "gauntlet006",
      en: "Pulsation Bracer",
      kr: "격동의 조력",
      jp: "パルスの機腕",
      zh: "脉冲协臂",
      imgKey: "ico006",
    },
    gauntlet007:{ //* 루크 헤르센
			id: "gauntlet007",
      en: "Daybreaker's Spine",
      kr: "한낮의 의지",
      jp: "デイブレイカースパイン",
      zh: "白昼之脊",
      imgKey: "ico007",
    },
    
    //$ 4-Starts
    gauntlet101:{
			id: "gauntlet101",
      en: "Marcato",
      kr: "바람의 악센트",
      jp: "狂乱マルカート",
      zh: "呼啸重音",
      imgKey: "ico101",
    },
    gauntlet102:{
			id: "gauntlet102",
      en: "Gauntlets#21D",
      kr: "21형 권갑 · 아이언 팬텀",
      jp: "鋼影拳＃21・四番",
      zh: "钢影拳-21丁型",
      imgKey: "ico102",
    },
    gauntlet103:{
			id: "gauntlet103",
      en: "Amity Accord",
      kr: "전우의 의리",
      jp: "金鉄の志",
      zh: "袍泽之固",
      imgKey: "ico103",
    },
    gauntlet104:{
			id: "gauntlet104",
      en: "Hollow Mirage",
      kr: "천공의 역행",
      jp: "驚異の星",
      zh: "骇行",
      imgKey: "ico104",
    },
    gauntlet105:{
			id: "gauntlet105",
      en: "Stonard",
      kr: "황금 권갑",
      jp: "黄金の拳",
      zh: "金掌",
      imgKey: "ico105",
    },
    gauntlet106:{
			id: "gauntlet106",
      en: "Celestial Spiral",
      kr: "천상의 나선",
      jp: "星屑が捩れる渦巻腕",
      zh: "尘云旋臂",
      imgKey: "ico106",
    },
    gauntlet107:{
			id: "gauntlet107",
      en: "Legend of Drunken Hero",
      kr: "만취의 영웅지",
      jp: "酩酊のエポス",
      zh: "酩酊的英雄志",
      imgKey: "ico107",
    },
    gauntlet108:{
			id: "gauntlet108",
      en: "Aether Strike",
      kr: "거침없는 비상",
      jp: "舞い上がる大空",
      zh: "凌空",
      imgKey: "ico108",
    },
  },
  pistol: { //* 권총
    //$ 5-Starts
    pistol001:{
			id: "pistol001",
      en: "Static Mist",
      kr: "부동의 안개",
      jp: "不変の湖煙",
      zh: "停驻之烟",
      imgKey: "ico001",
    },
    pistol002:{
			id: "pistol002",
      en: "The Last Dance",
      kr: "죽음과 춤",
      jp: "ラストダンス",
      zh: "死与舞",
      imgKey: "ico002",
    },
    pistol003:{
			id: "pistol003",
      en: "Woodland Aria",
      kr: "숲속의 아리아",
      jp: "森のアリア",
      zh: "林间的咏叹调",
      imgKey: "ico003",
    },
    pistol004:{
			id: "pistol004",
      en: "Lux & Umbra",
      kr: "얽혀진 빛과 그림자",
      jp: "ルクス＆アンブラ",
      zh: "光影双生",
      imgKey: "ico004",
    },
    pistol005:{ //* 신상시
			id: "pistol005",
      en: "Phasic Homogenizer",
      kr: "위상의 파동",
      jp: "フェーズのさざ波",
      zh: "相位涟漪",
      imgKey: "ico005",
    },
    pistol006:{//* 린네
			id: "pistol006",
      en: "Spectrum Blaster",
      kr: "스펙트럼 블래스터",
      jp: "スペクトル・ブラスター",
      zh: "溢彩荧辉",
      imgKey: "ico006",
    },
    //$ 4-Starts
    pistol101:{
			id: "pistol101",
      en: "Cadenza",
      kr: "화려한 악곡",
      jp: "華麗カテンツァ",
      zh: "华彩乐段",
      imgKey: "ico101",
    },
    pistol102:{
			id: "pistol102",
      en: "Pistols#26",
      kr: "26형 권총 · 맹렬한 돌격",
      jp: "穿撃銃＃26",
      zh: "穿击枪-26型",
      imgKey: "ico102",
    },
    pistol103:{
			id: "pistol103",
      en: "Undying Flame",
      kr: "불멸의 성화",
      jp: "燃え尽きぬ焔",
      zh: "无眠烈火",
      imgKey: "ico103",
    },
    pistol104:{
			id: "pistol104",
      en: "Novaburst",
      kr: "천공의 순간",
      jp: "疾走の星",
      zh: "飞逝",
      imgKey: "ico104",
    },
    pistol105:{
			id: "pistol105",
      en: "Thunderbolt",
      kr: "뇌전",
      jp: "迸る雷霆",
      zh: "奔雷",
      imgKey: "ico105",
    },
    pistol106:{
			id: "pistol106",
      en: "Relativistic Jet",
      kr: "역설의 격류",
      jp: "悖理を説く宇宙ジェット",
      zh: "悖论喷流",
      imgKey: "ico106",
    },
    pistol107:{
			id: "pistol107",
      en: "Romance in Farewell",
      kr: "작별의 로맨스",
      jp: "別れのメロス",
      zh: "叙别的罗曼史",
      imgKey: "ico107",
    },
    pistol108:{
			id: "pistol108",
      en: "Solar Flame",
      kr: "태양 불꽃",
      jp: "別れのメロス",
      zh: "紅炎",
      imgKey: "ico108",
    },
  },
  rectifier: { //* 증폭기
    //$ 5-Starts
    rectifier001:{
			id: "rectifier001",
      en: "Cosmic Ripples",
      kr: "파도의 기록",
      jp: "栄枯の湖岸",
      zh: "漪澜浮录",
      imgKey: "ico001",
    },
    rectifier002:{
			id: "rectifier002",
      en: "Stringmaster",
      kr: "꼭두각시의 손",
      jp: "糸繰りの奇術",
      zh: "掣傀之手",
      imgKey: "ico002",
    },
    rectifier003:{
			id: "rectifier003",
      en: "Rime-Draped Sprouts",
      kr: "옥수 비단",
      jp: "氷華の雅印",
      zh: "琼枝冰绡",
      imgKey: "ico003",
    },
    rectifier004:{
			id: "rectifier004",
      en: "Stellar Symphony",
      kr: "뭇별의 교향곡",
      jp: "星々のコンチェルト",
      zh: "星序协响",
      imgKey: "ico004",
    },
    rectifier005:{
			id: "rectifier005",
      en: "Luminous Hymn",
      kr: "광휘의 찬송가",
      jp: "光のハルモニア",
      zh: "和光回唱",
      imgKey: "ico005",
    },
    rectifier006:{
			id: "rectifier006",
      en: "Whispers of Sirens",
      kr: "바다의 속삭임",
      jp: "深海の囁き",
      zh: "海的呢喃",
      imgKey: "ico006",
    },
    rectifier007:{
			id: "rectifier007",
      en: "Lethean Elegy",
      kr: "잊혀진 피안의 슬픈 악장",
      jp: "幽冥の忘憂曲",
      zh: "幽冥的忘忧章",
      imgKey: "ico007",
    },
    rectifier008:{//* 신상시
			id: "rectifier008",
      en: "Boson Astrolabe",
      kr: "보손 관측기",
      jp: "ボゾンの観測器",
      zh: "玻色星仪",
      imgKey: "ico008",
    },
    //$ 4-Starts
    rectifier101:{
			id: "rectifier101",
      en: "Call of the Abyss",
      kr: "심해의 메아리",
      jp: "海淵のリフレイン",
      zh: "渊海回声",
      imgKey: "ico101",
    },
    rectifier102:{
			id: "rectifier102",
      en: "Variation",
      kr: "판타지 변주",
      jp: "奇妙バリエーション",
      zh: "奇幻变奏",
      imgKey: "ico102",
    },
    rectifier103:{
			id: "rectifier103",
      en: "Ocean's Gift",
      kr: "바다의 선물",
      jp: "海の恩恵",
      zh: "大海的馈赠",
      imgKey: "ico103",
    },
    rectifier104:{
			id: "rectifier104",
      en: "Rectifier#25",
      kr: "25형 증폭기 · 울림의 멜로디",
      jp: "鳴動機＃25",
      zh: "鸣动仪-25型",
      imgKey: "ico104",
    },
    rectifier105:{
			id: "rectifier105",
      en: "Jinzhou Keeper",
      kr: "금주의 수호",
      jp: "今州の衛士",
      zh: "今州守望",
      imgKey: "ico105",
    },
    rectifier106:{
			id: "rectifier106",
      en: "Comet Flare",
      kr: "굉음",
      jp: "変化の星",
      zh: "异度",
      imgKey: "ico106",
    },
    rectifier107:{
			id: "rectifier107",
      en: "Augment",
      kr: "청음",
      jp: "清らかな音",
      zh: "清音",
      imgKey: "ico107",
    },
    rectifier108:{
			id: "rectifier108",
      en: "Fusion Accretion",
      kr: "융합의 원반",
      jp: "コアが溶融する降着円盤",
      zh: "核熔星盘",
      imgKey: "ico108",
    },
    rectifier109:{
			id: "rectifier109",
      en: "Waltz in Masquerade",
      kr: "허위의 왈츠",
      jp: "虚飾のワルツ",
      zh: "虚饰的华尔兹",
      imgKey: "ico109",
    },
    rectifier110:{
			id: "rectifier110",
      en: "Radiant Dawn",
      kr: "눈부신 빛",
      jp: "弾む輝き",
      zh: "曜光",
      imgKey: "ico110",
    },
  },
} as const satisfies Record<WeaponType, Record<string, Weapon>>;

export const weaponDict: Record<WeaponId, Weapon> = {
  ...weapon.sword,
  ...weapon.broadblade,
  ...weapon.gauntlet,
  ...weapon.pistol,
  ...weapon.rectifier,
  dummy: {
    id: "dummy",
    en: "dummy",
    kr: "dummy",
    jp: "dummy",
    zh: "dummy",
    imgKey: "default",
  },
};